// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(AlignReferenceJsonConverter))]
    public enum AlignReference {
        Top,
        Right,
        Bottom,
        Left,
        Middle,
        Center,
    }

    internal static class AlignReferenceExtensions {
        public static string ToWireValue(this AlignReference value) {
            return value switch
            {
                AlignReference.Top => "Top",
                AlignReference.Right => "Right",
                AlignReference.Bottom => "Bottom",
                AlignReference.Left => "Left",
                AlignReference.Middle => "Middle",
                AlignReference.Center => "Center",
                _ => value.ToString(),
            };
        }

        public static AlignReference ParseAlignReference(this string value) {
            return value switch
            {
                "Top" => AlignReference.Top,
                "Right" => AlignReference.Right,
                "Bottom" => AlignReference.Bottom,
                "Left" => AlignReference.Left,
                "Middle" => AlignReference.Middle,
                "Center" => AlignReference.Center,
                _ => throw new System.ArgumentException($"Unknown AlignReference value: {value}"),
            };
        }
    }

    internal sealed class AlignReferenceJsonConverter : System.Text.Json.Serialization.JsonConverter<AlignReference> {
        public override AlignReference Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseAlignReference();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, AlignReference value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
