// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class ApplicationImageDto {
        [JsonPropertyName("file")]
        public FileDto? File { get; set; }

        [JsonPropertyName("fileId")]
        public int? FileId { get; set; }

        [JsonPropertyName("height")]
        public int? Height { get; set; }

        [JsonPropertyName("horizontalResolution")]
        public float? HorizontalResolution { get; set; }

        [JsonPropertyName("id")]
        public int? Id { get; set; }

        [JsonPropertyName("imageFormat")]
        public string? ImageFormat { get; set; }

        [JsonPropertyName("url")]
        public string? Url { get; set; }

        [JsonPropertyName("verticalResolution")]
        public float? VerticalResolution { get; set; }

        [JsonPropertyName("width")]
        public int? Width { get; set; }

    }
}
