// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class BarcodeReadSettingsDto {
        [JsonPropertyName("acquisitionPresetName")]
        public string? AcquisitionPresetName { get; set; }

        [JsonPropertyName("angle")]
        public float Angle { get; set; }

        [JsonPropertyName("cameraId")]
        public string? CameraId { get; set; }

        [JsonPropertyName("canBeDeleted")]
        public bool? CanBeDeleted { get; set; }

        [JsonPropertyName("format")]
        public BarcodeFormat Format { get; set; }

        [JsonPropertyName("id")]
        public int Id { get; set; }

        [JsonPropertyName("name")]
        public string? Name { get; set; }

        [JsonPropertyName("roi")]
        public Rectangle Roi { get; set; } = default!;

        [JsonPropertyName("scannerId")]
        public string? ScannerId { get; set; }

    }
}
