// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(BarcodeFormatJsonConverter))]
    public enum BarcodeFormat {
        Unrecognized,
        Aztec,
        Codabar,
        Code39,
        Code93,
        Code128,
        DataMatrix,
        Ean8,
        Ean13,
        Itf,
        Maxicode,
        Pdf417,
        QrCode,
        Rss14,
        RssExpanded,
        UpcA,
        UpcE,
        UpcEanExtension,
        Msi,
        Plessey,
        Imb,
        PharmaCode,
    }

    internal static class BarcodeFormatExtensions {
        public static string ToWireValue(this BarcodeFormat value) {
            return value switch
            {
                BarcodeFormat.Unrecognized => "UNRECOGNIZED",
                BarcodeFormat.Aztec => "AZTEC",
                BarcodeFormat.Codabar => "CODABAR",
                BarcodeFormat.Code39 => "CODE_39",
                BarcodeFormat.Code93 => "CODE_93",
                BarcodeFormat.Code128 => "CODE_128",
                BarcodeFormat.DataMatrix => "DATA_MATRIX",
                BarcodeFormat.Ean8 => "EAN_8",
                BarcodeFormat.Ean13 => "EAN_13",
                BarcodeFormat.Itf => "ITF",
                BarcodeFormat.Maxicode => "MAXICODE",
                BarcodeFormat.Pdf417 => "PDF_417",
                BarcodeFormat.QrCode => "QR_CODE",
                BarcodeFormat.Rss14 => "RSS_14",
                BarcodeFormat.RssExpanded => "RSS_EXPANDED",
                BarcodeFormat.UpcA => "UPC_A",
                BarcodeFormat.UpcE => "UPC_E",
                BarcodeFormat.UpcEanExtension => "UPC_EAN_EXTENSION",
                BarcodeFormat.Msi => "MSI",
                BarcodeFormat.Plessey => "PLESSEY",
                BarcodeFormat.Imb => "IMB",
                BarcodeFormat.PharmaCode => "PHARMA_CODE",
                _ => value.ToString(),
            };
        }

        public static BarcodeFormat ParseBarcodeFormat(this string value) {
            return value switch
            {
                "UNRECOGNIZED" => BarcodeFormat.Unrecognized,
                "AZTEC" => BarcodeFormat.Aztec,
                "CODABAR" => BarcodeFormat.Codabar,
                "CODE_39" => BarcodeFormat.Code39,
                "CODE_93" => BarcodeFormat.Code93,
                "CODE_128" => BarcodeFormat.Code128,
                "DATA_MATRIX" => BarcodeFormat.DataMatrix,
                "EAN_8" => BarcodeFormat.Ean8,
                "EAN_13" => BarcodeFormat.Ean13,
                "ITF" => BarcodeFormat.Itf,
                "MAXICODE" => BarcodeFormat.Maxicode,
                "PDF_417" => BarcodeFormat.Pdf417,
                "QR_CODE" => BarcodeFormat.QrCode,
                "RSS_14" => BarcodeFormat.Rss14,
                "RSS_EXPANDED" => BarcodeFormat.RssExpanded,
                "UPC_A" => BarcodeFormat.UpcA,
                "UPC_E" => BarcodeFormat.UpcE,
                "UPC_EAN_EXTENSION" => BarcodeFormat.UpcEanExtension,
                "MSI" => BarcodeFormat.Msi,
                "PLESSEY" => BarcodeFormat.Plessey,
                "IMB" => BarcodeFormat.Imb,
                "PHARMA_CODE" => BarcodeFormat.PharmaCode,
                _ => throw new System.ArgumentException($"Unknown BarcodeFormat value: {value}"),
            };
        }
    }

    internal sealed class BarcodeFormatJsonConverter : System.Text.Json.Serialization.JsonConverter<BarcodeFormat> {
        public override BarcodeFormat Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseBarcodeFormat();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, BarcodeFormat value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
