// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(BoxModuleDoorStatusJsonConverter))]
    public enum BoxModuleDoorStatus {
        Closed,
        FrontOpen,
        RearOpen,
        RejectOpen,
    }

    internal static class BoxModuleDoorStatusExtensions {
        public static string ToWireValue(this BoxModuleDoorStatus value) {
            return value switch
            {
                BoxModuleDoorStatus.Closed => "Closed",
                BoxModuleDoorStatus.FrontOpen => "FrontOpen",
                BoxModuleDoorStatus.RearOpen => "RearOpen",
                BoxModuleDoorStatus.RejectOpen => "RejectOpen",
                _ => value.ToString(),
            };
        }

        public static BoxModuleDoorStatus ParseBoxModuleDoorStatus(this string value) {
            return value switch
            {
                "Closed" => BoxModuleDoorStatus.Closed,
                "FrontOpen" => BoxModuleDoorStatus.FrontOpen,
                "RearOpen" => BoxModuleDoorStatus.RearOpen,
                "RejectOpen" => BoxModuleDoorStatus.RejectOpen,
                _ => throw new System.ArgumentException($"Unknown BoxModuleDoorStatus value: {value}"),
            };
        }
    }

    internal sealed class BoxModuleDoorStatusJsonConverter : System.Text.Json.Serialization.JsonConverter<BoxModuleDoorStatus> {
        public override BoxModuleDoorStatus Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseBoxModuleDoorStatus();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, BoxModuleDoorStatus value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
