// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class BoxModuleStateChangedEventNotification {
        [JsonPropertyName("eventData")]
        public BoxModuleState? EventData { get; set; }

        [JsonPropertyName("moduleId")]
        public string? ModuleId { get; set; }

        [JsonPropertyName("nodeId")]
        public string? NodeId { get; set; }

    }
}
