// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class CameraSettingsDto {
        [JsonPropertyName("binningMode")]
        public BinningMode? BinningMode { get; set; }

        [JsonPropertyName("exposureMicroseconds")]
        public int? ExposureMicroseconds { get; set; }

        [JsonPropertyName("gainDb")]
        public double? GainDb { get; set; }

        [JsonPropertyName("mirroringMode")]
        public MirroringMode? MirroringMode { get; set; }

        [JsonPropertyName("name")]
        public string? Name { get; set; }

        [JsonPropertyName("roi")]
        public RectangleDto? Roi { get; set; }

        [JsonPropertyName("rotationAngle")]
        public int? RotationAngle { get; set; }

        [JsonPropertyName("rotationEnabled")]
        public bool? RotationEnabled { get; set; }

    }
}
