// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(CameraTypeJsonConverter))]
    public enum CameraType {
        MockCamera,
        MvBlueFox,
        VideoCapture,
    }

    internal static class CameraTypeExtensions {
        public static string ToWireValue(this CameraType value) {
            return value switch
            {
                CameraType.MockCamera => "MockCamera",
                CameraType.MvBlueFox => "MvBlueFox",
                CameraType.VideoCapture => "VideoCapture",
                _ => value.ToString(),
            };
        }

        public static CameraType ParseCameraType(this string value) {
            return value switch
            {
                "MockCamera" => CameraType.MockCamera,
                "MvBlueFox" => CameraType.MvBlueFox,
                "VideoCapture" => CameraType.VideoCapture,
                _ => throw new System.ArgumentException($"Unknown CameraType value: {value}"),
            };
        }
    }

    internal sealed class CameraTypeJsonConverter : System.Text.Json.Serialization.JsonConverter<CameraType> {
        public override CameraType Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseCameraType();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, CameraType value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
