// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class ChipReadBackMessage : WorkflowMessage {
        [JsonPropertyName("callbackUrl")]
        public string? CallbackUrl { get; set; }

        [JsonPropertyName("encoderId")]
        public string? EncoderId { get; set; }

        [JsonPropertyName("encoderIndex")]
        public int? EncoderIndex { get; set; }

    }
}
