// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(CleanAtStartupStatusJsonConverter))]
    public enum CleanAtStartupStatus {
        Disabled,
        Idle,
        WaitingForTemperature,
        PerformingCleaning,
        Done,
        Failed,
    }

    internal static class CleanAtStartupStatusExtensions {
        public static string ToWireValue(this CleanAtStartupStatus value) {
            return value switch
            {
                CleanAtStartupStatus.Disabled => "Disabled",
                CleanAtStartupStatus.Idle => "Idle",
                CleanAtStartupStatus.WaitingForTemperature => "WaitingForTemperature",
                CleanAtStartupStatus.PerformingCleaning => "PerformingCleaning",
                CleanAtStartupStatus.Done => "Done",
                CleanAtStartupStatus.Failed => "Failed",
                _ => value.ToString(),
            };
        }

        public static CleanAtStartupStatus ParseCleanAtStartupStatus(this string value) {
            return value switch
            {
                "Disabled" => CleanAtStartupStatus.Disabled,
                "Idle" => CleanAtStartupStatus.Idle,
                "WaitingForTemperature" => CleanAtStartupStatus.WaitingForTemperature,
                "PerformingCleaning" => CleanAtStartupStatus.PerformingCleaning,
                "Done" => CleanAtStartupStatus.Done,
                "Failed" => CleanAtStartupStatus.Failed,
                _ => throw new System.ArgumentException($"Unknown CleanAtStartupStatus value: {value}"),
            };
        }
    }

    internal sealed class CleanAtStartupStatusJsonConverter : System.Text.Json.Serialization.JsonConverter<CleanAtStartupStatus> {
        public override CleanAtStartupStatus Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseCleanAtStartupStatus();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, CleanAtStartupStatus value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
