// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class CreateLineDto {
        [JsonPropertyName("end")]
        public Point2fDto? End { get; set; }

        [JsonPropertyName("name")]
        public string? Name { get; set; }

        [JsonPropertyName("start")]
        public Point2fDto? Start { get; set; }

    }
}
