// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class CreateDataSourceDto {
        [JsonPropertyName("connectionString")]
        public string? ConnectionString { get; set; }

        [JsonPropertyName("dataSourceType")]
        public DataSourceType? DataSourceType { get; set; }

        [JsonPropertyName("description")]
        public string? Description { get; set; }

        [JsonPropertyName("name")]
        public string? Name { get; set; }

        [JsonPropertyName("queryTemplate")]
        public string? QueryTemplate { get; set; }

        [JsonPropertyName("tableName")]
        public string? TableName { get; set; }

    }
}
