// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class CreateJobTemplateLayoutAutoPosSettingsDto {
        [JsonPropertyName("name")]
        public string? Name { get; set; }

        [JsonPropertyName("templateMatchingConfigurationId")]
        public int? TemplateMatchingConfigurationId { get; set; }

        [JsonPropertyName("threshold")]
        public float? Threshold { get; set; }

    }
}
