// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class CuringSettingsRequest {
        [JsonPropertyName("curingEnabled")]
        public bool? CuringEnabled { get; set; }

        [JsonPropertyName("dualCuringEnabled")]
        public bool? DualCuringEnabled { get; set; }

        [JsonPropertyName("fastCuringEnabled")]
        public bool? FastCuringEnabled { get; set; }

        [JsonPropertyName("level")]
        public int? Level { get; set; }

        [JsonPropertyName("speed")]
        public int? Speed { get; set; }

    }
}
