// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class DataRecordField {
        [JsonPropertyName("index")]
        public int? Index { get; set; }

        [JsonPropertyName("value")]
        public string? Value { get; set; }

    }
}
