// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class DesignLayer {
        [JsonPropertyName("colorProfileId")]
        public ColorProfileId? ColorProfileId { get; set; }

        [JsonPropertyName("elements")]
        public global::System.Collections.Generic.IList<DesignElement>? Elements { get; set; }

        [JsonPropertyName("height")]
        public float Height { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; } = default!;

        [JsonPropertyName("numberOfPrints")]
        public int? NumberOfPrints { get; set; }

        [JsonPropertyName("pageId")]
        public int? PageId { get; set; }

        [JsonPropertyName("printQuality")]
        public LayerPrintQuality? PrintQuality { get; set; }

        [JsonPropertyName("rotation")]
        public float? Rotation { get; set; }

        [JsonPropertyName("width")]
        public float Width { get; set; }

        [JsonPropertyName("x")]
        public float? X { get; set; }

        [JsonPropertyName("y")]
        public float? Y { get; set; }

        [JsonPropertyName("zIndex")]
        public float? ZIndex { get; set; }

    }
}
