// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(DeviceTypeJsonConverter))]
    public enum DeviceType {
        Camera,
        Encoder,
        LightSource,
        Transport,
        LaserBoard,
        Laser,
        BarcodeReader,
        MagneticStripeEncoder,
        InkjetBoard,
    }

    internal static class DeviceTypeExtensions {
        public static string ToWireValue(this DeviceType value) {
            return value switch
            {
                DeviceType.Camera => "Camera",
                DeviceType.Encoder => "Encoder",
                DeviceType.LightSource => "LightSource",
                DeviceType.Transport => "Transport",
                DeviceType.LaserBoard => "LaserBoard",
                DeviceType.Laser => "Laser",
                DeviceType.BarcodeReader => "BarcodeReader",
                DeviceType.MagneticStripeEncoder => "MagneticStripeEncoder",
                DeviceType.InkjetBoard => "InkjetBoard",
                _ => value.ToString(),
            };
        }

        public static DeviceType ParseDeviceType(this string value) {
            return value switch
            {
                "Camera" => DeviceType.Camera,
                "Encoder" => DeviceType.Encoder,
                "LightSource" => DeviceType.LightSource,
                "Transport" => DeviceType.Transport,
                "LaserBoard" => DeviceType.LaserBoard,
                "Laser" => DeviceType.Laser,
                "BarcodeReader" => DeviceType.BarcodeReader,
                "MagneticStripeEncoder" => DeviceType.MagneticStripeEncoder,
                "InkjetBoard" => DeviceType.InkjetBoard,
                _ => throw new System.ArgumentException($"Unknown DeviceType value: {value}"),
            };
        }
    }

    internal sealed class DeviceTypeJsonConverter : System.Text.Json.Serialization.JsonConverter<DeviceType> {
        public override DeviceType Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseDeviceType();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, DeviceType value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
