// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(DiagnosticTaskTypeJsonConverter))]
    public enum DiagnosticTaskType {
        None,
        Transport,
        Autopos,
        Ocr,
        Laser,
        MagStripe,
    }

    internal static class DiagnosticTaskTypeExtensions {
        public static string ToWireValue(this DiagnosticTaskType value) {
            return value switch
            {
                DiagnosticTaskType.None => "None",
                DiagnosticTaskType.Transport => "Transport",
                DiagnosticTaskType.Autopos => "Autopos",
                DiagnosticTaskType.Ocr => "Ocr",
                DiagnosticTaskType.Laser => "Laser",
                DiagnosticTaskType.MagStripe => "MagStripe",
                _ => value.ToString(),
            };
        }

        public static DiagnosticTaskType ParseDiagnosticTaskType(this string value) {
            return value switch
            {
                "None" => DiagnosticTaskType.None,
                "Transport" => DiagnosticTaskType.Transport,
                "Autopos" => DiagnosticTaskType.Autopos,
                "Ocr" => DiagnosticTaskType.Ocr,
                "Laser" => DiagnosticTaskType.Laser,
                "MagStripe" => DiagnosticTaskType.MagStripe,
                _ => throw new System.ArgumentException($"Unknown DiagnosticTaskType value: {value}"),
            };
        }
    }

    internal sealed class DiagnosticTaskTypeJsonConverter : System.Text.Json.Serialization.JsonConverter<DiagnosticTaskType> {
        public override DiagnosticTaskType Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseDiagnosticTaskType();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, DiagnosticTaskType value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
