// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(DipSwitchSettingJsonConverter))]
    public enum DipSwitchSetting {
        SingleFeeder,
        DualFeeder,
        Stacker,
        MagStripeReader,
        MultiChip,
        InkJet,
        Unused1,
        Unused2,
    }

    internal static class DipSwitchSettingExtensions {
        public static string ToWireValue(this DipSwitchSetting value) {
            return value switch
            {
                DipSwitchSetting.SingleFeeder => "SingleFeeder",
                DipSwitchSetting.DualFeeder => "DualFeeder",
                DipSwitchSetting.Stacker => "Stacker",
                DipSwitchSetting.MagStripeReader => "MagStripeReader",
                DipSwitchSetting.MultiChip => "MultiChip",
                DipSwitchSetting.InkJet => "InkJet",
                DipSwitchSetting.Unused1 => "Unused_1",
                DipSwitchSetting.Unused2 => "Unused_2",
                _ => value.ToString(),
            };
        }

        public static DipSwitchSetting ParseDipSwitchSetting(this string value) {
            return value switch
            {
                "SingleFeeder" => DipSwitchSetting.SingleFeeder,
                "DualFeeder" => DipSwitchSetting.DualFeeder,
                "Stacker" => DipSwitchSetting.Stacker,
                "MagStripeReader" => DipSwitchSetting.MagStripeReader,
                "MultiChip" => DipSwitchSetting.MultiChip,
                "InkJet" => DipSwitchSetting.InkJet,
                "Unused_1" => DipSwitchSetting.Unused1,
                "Unused_2" => DipSwitchSetting.Unused2,
                _ => throw new System.ArgumentException($"Unknown DipSwitchSetting value: {value}"),
            };
        }
    }

    internal sealed class DipSwitchSettingJsonConverter : System.Text.Json.Serialization.JsonConverter<DipSwitchSetting> {
        public override DipSwitchSetting Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseDipSwitchSetting();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, DipSwitchSetting value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
