// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(FeederStatusJsonConverter))]
    public enum FeederStatus {
        Disconnected,
        FeederEmpty,
        Ready,
    }

    internal static class FeederStatusExtensions {
        public static string ToWireValue(this FeederStatus value) {
            return value switch
            {
                FeederStatus.Disconnected => "Disconnected",
                FeederStatus.FeederEmpty => "FeederEmpty",
                FeederStatus.Ready => "Ready",
                _ => value.ToString(),
            };
        }

        public static FeederStatus ParseFeederStatus(this string value) {
            return value switch
            {
                "Disconnected" => FeederStatus.Disconnected,
                "FeederEmpty" => FeederStatus.FeederEmpty,
                "Ready" => FeederStatus.Ready,
                _ => throw new System.ArgumentException($"Unknown FeederStatus value: {value}"),
            };
        }
    }

    internal sealed class FeederStatusJsonConverter : System.Text.Json.Serialization.JsonConverter<FeederStatus> {
        public override FeederStatus Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseFeederStatus();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, FeederStatus value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
