// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class FilterDto {
        [JsonPropertyName("fieldName")]
        public string? FieldName { get; set; }

        [JsonPropertyName("value")]
        public global::System.Collections.Generic.IList<string>? Value { get; set; }

    }
}
