// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(FluidKindJsonConverter))]
    public enum FluidKind {
        Dummy,
        Color,
        Varnish,
        Flush,
        None,
    }

    internal static class FluidKindExtensions {
        public static string ToWireValue(this FluidKind value) {
            return value switch
            {
                FluidKind.Dummy => "Dummy",
                FluidKind.Color => "Color",
                FluidKind.Varnish => "Varnish",
                FluidKind.Flush => "Flush",
                FluidKind.None => "None",
                _ => value.ToString(),
            };
        }

        public static FluidKind ParseFluidKind(this string value) {
            return value switch
            {
                "Dummy" => FluidKind.Dummy,
                "Color" => FluidKind.Color,
                "Varnish" => FluidKind.Varnish,
                "Flush" => FluidKind.Flush,
                "None" => FluidKind.None,
                _ => throw new System.ArgumentException($"Unknown FluidKind value: {value}"),
            };
        }
    }

    internal sealed class FluidKindJsonConverter : System.Text.Json.Serialization.JsonConverter<FluidKind> {
        public override FluidKind Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseFluidKind();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, FluidKind value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
