// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class HeadAxisSettings {
        [JsonPropertyName("accelerationSteps")]
        public int? AccelerationSteps { get; set; }

        [JsonPropertyName("cappingPosition")]
        public float? CappingPosition { get; set; }

        [JsonPropertyName("decelerationSteps")]
        public int? DecelerationSteps { get; set; }

        [JsonPropertyName("diagSpeed")]
        public int? DiagSpeed { get; set; }

        [JsonPropertyName("homingSpeed")]
        public int? HomingSpeed { get; set; }

        [JsonPropertyName("mainSpeed")]
        public int? MainSpeed { get; set; }

        [JsonPropertyName("posAxisCalibration")]
        public float? PosAxisCalibration { get; set; }

        [JsonPropertyName("posHeadCalibration")]
        public float? PosHeadCalibration { get; set; }

        [JsonPropertyName("printArea")]
        public float? PrintArea { get; set; }

        [JsonPropertyName("tvalAcc")]
        public int? TvalAcc { get; set; }

        [JsonPropertyName("tvalDec")]
        public int? TvalDec { get; set; }

        [JsonPropertyName("tvalHold")]
        public int? TvalHold { get; set; }

        [JsonPropertyName("tvalRun")]
        public int? TvalRun { get; set; }

    }
}
