// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class ImportRegistersRequest {
        [JsonPropertyName("com")]
        public string? Com { get; set; }

        [JsonPropertyName("registers")]
        public global::System.Collections.Generic.IList<ModbusRegister>? Registers { get; set; }

        [JsonPropertyName("slaveId")]
        public int SlaveId { get; set; }

    }
}
