// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(InkjetPrinterActionKindJsonConverter))]
    public enum InkjetPrinterActionKind {
        PrintDocument,
        ParkPrintHead,
        AutoClean,
        LightCleaning,
        NormalCleaning,
        StrongCleaning,
        StrongPurge,
        Spit,
        WarmPrintHead,
        EnterMaintenance,
        ExitMaintenance,
        ParkPrinthead,
        VacuumTest,
        InkPriming,
        InkEmptying,
        Resetting,
        MaintenanceMode,
        ShuttingDown,
        Cleaning,
        PrintheadWiping,
        ChecksForPrint,
        ImageUploaded,
        CustomCleaning,
    }

    internal static class InkjetPrinterActionKindExtensions {
        public static string ToWireValue(this InkjetPrinterActionKind value) {
            return value switch
            {
                InkjetPrinterActionKind.PrintDocument => "PrintDocument",
                InkjetPrinterActionKind.ParkPrintHead => "ParkPrintHead",
                InkjetPrinterActionKind.AutoClean => "AutoClean",
                InkjetPrinterActionKind.LightCleaning => "LightCleaning",
                InkjetPrinterActionKind.NormalCleaning => "NormalCleaning",
                InkjetPrinterActionKind.StrongCleaning => "StrongCleaning",
                InkjetPrinterActionKind.StrongPurge => "StrongPurge",
                InkjetPrinterActionKind.Spit => "Spit",
                InkjetPrinterActionKind.WarmPrintHead => "WarmPrintHead",
                InkjetPrinterActionKind.EnterMaintenance => "EnterMaintenance",
                InkjetPrinterActionKind.ExitMaintenance => "ExitMaintenance",
                InkjetPrinterActionKind.ParkPrinthead => "ParkPrinthead",
                InkjetPrinterActionKind.VacuumTest => "VacuumTest",
                InkjetPrinterActionKind.InkPriming => "InkPriming",
                InkjetPrinterActionKind.InkEmptying => "InkEmptying",
                InkjetPrinterActionKind.Resetting => "Resetting",
                InkjetPrinterActionKind.MaintenanceMode => "MaintenanceMode",
                InkjetPrinterActionKind.ShuttingDown => "ShuttingDown",
                InkjetPrinterActionKind.Cleaning => "Cleaning",
                InkjetPrinterActionKind.PrintheadWiping => "PrintheadWiping",
                InkjetPrinterActionKind.ChecksForPrint => "ChecksForPrint",
                InkjetPrinterActionKind.ImageUploaded => "ImageUploaded",
                InkjetPrinterActionKind.CustomCleaning => "CustomCleaning",
                _ => value.ToString(),
            };
        }

        public static InkjetPrinterActionKind ParseInkjetPrinterActionKind(this string value) {
            return value switch
            {
                "PrintDocument" => InkjetPrinterActionKind.PrintDocument,
                "ParkPrintHead" => InkjetPrinterActionKind.ParkPrintHead,
                "AutoClean" => InkjetPrinterActionKind.AutoClean,
                "LightCleaning" => InkjetPrinterActionKind.LightCleaning,
                "NormalCleaning" => InkjetPrinterActionKind.NormalCleaning,
                "StrongCleaning" => InkjetPrinterActionKind.StrongCleaning,
                "StrongPurge" => InkjetPrinterActionKind.StrongPurge,
                "Spit" => InkjetPrinterActionKind.Spit,
                "WarmPrintHead" => InkjetPrinterActionKind.WarmPrintHead,
                "EnterMaintenance" => InkjetPrinterActionKind.EnterMaintenance,
                "ExitMaintenance" => InkjetPrinterActionKind.ExitMaintenance,
                "ParkPrinthead" => InkjetPrinterActionKind.ParkPrinthead,
                "VacuumTest" => InkjetPrinterActionKind.VacuumTest,
                "InkPriming" => InkjetPrinterActionKind.InkPriming,
                "InkEmptying" => InkjetPrinterActionKind.InkEmptying,
                "Resetting" => InkjetPrinterActionKind.Resetting,
                "MaintenanceMode" => InkjetPrinterActionKind.MaintenanceMode,
                "ShuttingDown" => InkjetPrinterActionKind.ShuttingDown,
                "Cleaning" => InkjetPrinterActionKind.Cleaning,
                "PrintheadWiping" => InkjetPrinterActionKind.PrintheadWiping,
                "ChecksForPrint" => InkjetPrinterActionKind.ChecksForPrint,
                "ImageUploaded" => InkjetPrinterActionKind.ImageUploaded,
                "CustomCleaning" => InkjetPrinterActionKind.CustomCleaning,
                _ => throw new System.ArgumentException($"Unknown InkjetPrinterActionKind value: {value}"),
            };
        }
    }

    internal sealed class InkjetPrinterActionKindJsonConverter : System.Text.Json.Serialization.JsonConverter<InkjetPrinterActionKind> {
        public override InkjetPrinterActionKind Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseInkjetPrinterActionKind();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, InkjetPrinterActionKind value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
