// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(InputFeedersJsonConverter))]
    public enum InputFeeders {
        Any,
        Feeder1,
        Feeder2,
    }

    internal static class InputFeedersExtensions {
        public static string ToWireValue(this InputFeeders value) {
            return value switch
            {
                InputFeeders.Any => "Any",
                InputFeeders.Feeder1 => "Feeder1",
                InputFeeders.Feeder2 => "Feeder2",
                _ => value.ToString(),
            };
        }

        public static InputFeeders ParseInputFeeders(this string value) {
            return value switch
            {
                "Any" => InputFeeders.Any,
                "Feeder1" => InputFeeders.Feeder1,
                "Feeder2" => InputFeeders.Feeder2,
                _ => throw new System.ArgumentException($"Unknown InputFeeders value: {value}"),
            };
        }
    }

    internal sealed class InputFeedersJsonConverter : System.Text.Json.Serialization.JsonConverter<InputFeeders> {
        public override InputFeeders Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseInputFeeders();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, InputFeeders value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
