// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class InsertImageRequest {
        [JsonPropertyName("images")]
        public global::System.Collections.Generic.IList<FormFile>? Images { get; set; }

    }
}
