// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class JobInstanceDto {
        [JsonPropertyName("batchId")]
        public string? BatchId { get; set; }

        [JsonPropertyName("correlationId")]
        public string? CorrelationId { get; set; }

        [JsonPropertyName("createdAt")]
        public global::System.DateTimeOffset? CreatedAt { get; set; }

        [JsonPropertyName("currentPositionId")]
        public string? CurrentPositionId { get; set; }

        [JsonPropertyName("documentProduced")]
        public bool? DocumentProduced { get; set; }

        [JsonPropertyName("errorCodes")]
        public JobErrorCodes? ErrorCodes { get; set; }

        [JsonPropertyName("executingOperationId")]
        public string? ExecutingOperationId { get; set; }

        [JsonPropertyName("finishedAt")]
        public global::System.DateTimeOffset? FinishedAt { get; set; }

        [JsonPropertyName("id")]
        public int? Id { get; set; }

        [JsonPropertyName("jobId")]
        public string? JobId { get; set; }

        [JsonPropertyName("jobStatus")]
        public JobStatus? JobStatus { get; set; }

        [JsonPropertyName("persoOperations")]
        public global::System.Collections.Generic.IList<PersoOperationInstanceDto>? PersoOperations { get; set; }

        [JsonPropertyName("sessionId")]
        public string? SessionId { get; set; }

        [JsonPropertyName("startedAt")]
        public global::System.DateTimeOffset? StartedAt { get; set; }

        [JsonPropertyName("updatedAt")]
        public global::System.DateTimeOffset? UpdatedAt { get; set; }

        [JsonPropertyName("workflowInstanceId")]
        public string? WorkflowInstanceId { get; set; }

    }
}
