// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class JobTemplateOcrSettingsDto {
        [JsonPropertyName("id")]
        public int? Id { get; set; }

        [JsonPropertyName("jobTemplateId")]
        public int? JobTemplateId { get; set; }

        [JsonPropertyName("name")]
        public string? Name { get; set; }

        [JsonPropertyName("ocrSettings")]
        public OcrSettingsDto? OcrSettings { get; set; }

        [JsonPropertyName("ocrSettingsId")]
        public int? OcrSettingsId { get; set; }

        [JsonPropertyName("resultFieldName")]
        public string? ResultFieldName { get; set; }

        [JsonPropertyName("runBeforeMark")]
        public bool? RunBeforeMark { get; set; }

        [JsonPropertyName("sendWebhookNotification")]
        public bool? SendWebhookNotification { get; set; }

        [JsonPropertyName("supportSide")]
        public SupportSide? SupportSide { get; set; }

    }
}
