// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class JobTemplateInkjetLayoutDto {
        [JsonPropertyName("autoPosSettings")]
        public global::System.Collections.Generic.IList<JobTemplateInkjetLayoutAutoPosSettingsDto>? AutoPosSettings { get; set; }

        [JsonPropertyName("curingSettings")]
        public CuringSettingsDto? CuringSettings { get; set; }

        [JsonPropertyName("id")]
        public int? Id { get; set; }

        [JsonPropertyName("index")]
        public int? Index { get; set; }

        [JsonPropertyName("jobTemplateId")]
        public int? JobTemplateId { get; set; }

        [JsonPropertyName("layout")]
        public InkjetLayoutDto? Layout { get; set; }

        [JsonPropertyName("layoutId")]
        public int? LayoutId { get; set; }

        [JsonPropertyName("pinningSettings")]
        public PinningSettingsDto? PinningSettings { get; set; }

        [JsonPropertyName("printSettings")]
        public PrintSettingsDto? PrintSettings { get; set; }

        [JsonPropertyName("supportSide")]
        public string? SupportSide { get; set; }

    }
}
