// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class JobTemplateBarcodeReadSettingsDto {
        [JsonPropertyName("barcodeReadSettings")]
        public BarcodeReadSettingsDto? BarcodeReadSettings { get; set; }

        [JsonPropertyName("barcodeReadSettingsId")]
        public int? BarcodeReadSettingsId { get; set; }

        [JsonPropertyName("id")]
        public int? Id { get; set; }

        [JsonPropertyName("jobTemplateId")]
        public int? JobTemplateId { get; set; }

        [JsonPropertyName("name")]
        public string? Name { get; set; }

        [JsonPropertyName("supportSide")]
        public SupportSide? SupportSide { get; set; }

    }
}
