// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class LaserWorkflowJobDto {
        [JsonPropertyName("jobId")]
        public string? JobId { get; set; }

        [JsonPropertyName("operationId")]
        public int? OperationId { get; set; }

        [JsonPropertyName("operationType")]
        public PersoOperationTypes? OperationType { get; set; }

        [JsonPropertyName("status")]
        public LaserWorkflowJobStatus? Status { get; set; }

    }
}
