// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class LayoutXpOne {
        [JsonPropertyName("entities")]
        public global::System.Collections.Generic.IList<EntityXpOne>? Entities { get; set; }

        [JsonPropertyName("filePath")]
        public string? FilePath { get; set; }

        [JsonPropertyName("name")]
        public string? Name { get; set; }

    }
}
