// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class LoginRequest {
        [JsonPropertyName("ClientId")]
        public string? ClientId { get; set; }

        [JsonPropertyName("ClientSecret")]
        public string? ClientSecret { get; set; }

        [JsonPropertyName("Password")]
        public string? Password { get; set; }

        [JsonPropertyName("UserName")]
        public string? UserName { get; set; }

        [JsonPropertyName("redirectUrl")]
        public string? RedirectUrl { get; set; }

    }
}
