// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(MachineStateNotifierEventsJsonConverter))]
    public enum MachineStateNotifierEvents {
        BoxModuleTransportStatusChanged,
        ModuleStateChanged,
        LaserBoardStateChanged,
        SerialDataSent,
        SerialDataReceived,
        SystemStatusChanged,
        WorkflowSchedulerStateChanged,
        WorkflowInstanceStateChanged,
    }

    internal static class MachineStateNotifierEventsExtensions {
        public static string ToWireValue(this MachineStateNotifierEvents value) {
            return value switch
            {
                MachineStateNotifierEvents.BoxModuleTransportStatusChanged => "BoxModuleTransportStatusChanged",
                MachineStateNotifierEvents.ModuleStateChanged => "ModuleStateChanged",
                MachineStateNotifierEvents.LaserBoardStateChanged => "LaserBoardStateChanged",
                MachineStateNotifierEvents.SerialDataSent => "SerialDataSent",
                MachineStateNotifierEvents.SerialDataReceived => "SerialDataReceived",
                MachineStateNotifierEvents.SystemStatusChanged => "SystemStatusChanged",
                MachineStateNotifierEvents.WorkflowSchedulerStateChanged => "WorkflowSchedulerStateChanged",
                MachineStateNotifierEvents.WorkflowInstanceStateChanged => "WorkflowInstanceStateChanged",
                _ => value.ToString(),
            };
        }

        public static MachineStateNotifierEvents ParseMachineStateNotifierEvents(this string value) {
            return value switch
            {
                "BoxModuleTransportStatusChanged" => MachineStateNotifierEvents.BoxModuleTransportStatusChanged,
                "ModuleStateChanged" => MachineStateNotifierEvents.ModuleStateChanged,
                "LaserBoardStateChanged" => MachineStateNotifierEvents.LaserBoardStateChanged,
                "SerialDataSent" => MachineStateNotifierEvents.SerialDataSent,
                "SerialDataReceived" => MachineStateNotifierEvents.SerialDataReceived,
                "SystemStatusChanged" => MachineStateNotifierEvents.SystemStatusChanged,
                "WorkflowSchedulerStateChanged" => MachineStateNotifierEvents.WorkflowSchedulerStateChanged,
                "WorkflowInstanceStateChanged" => MachineStateNotifierEvents.WorkflowInstanceStateChanged,
                _ => throw new System.ArgumentException($"Unknown MachineStateNotifierEvents value: {value}"),
            };
        }
    }

    internal sealed class MachineStateNotifierEventsJsonConverter : System.Text.Json.Serialization.JsonConverter<MachineStateNotifierEvents> {
        public override MachineStateNotifierEvents Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseMachineStateNotifierEvents();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, MachineStateNotifierEvents value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
