// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class MagneticStripeReadBackMessage : WorkflowMessage {
        [JsonPropertyName("track1Base64")]
        public string? Track1Base64 { get; set; }

        [JsonPropertyName("track2Base64")]
        public string? Track2Base64 { get; set; }

        [JsonPropertyName("track3Base64")]
        public string? Track3Base64 { get; set; }

    }
}
