// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class MagneticReadBackConfigurationDto : ReadBackConfigurationDto {
        [JsonPropertyName("highCoercivity")]
        public bool? HighCoercivity { get; set; }

        [JsonPropertyName("readFromTrack1")]
        public bool? ReadFromTrack1 { get; set; }

        [JsonPropertyName("readFromTrack2")]
        public bool? ReadFromTrack2 { get; set; }

        [JsonPropertyName("readFromTrack3")]
        public bool? ReadFromTrack3 { get; set; }

    }
}
