// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class MagStripeDataDto {
        [JsonPropertyName("track1")]
        public string? Track1 { get; set; }

        [JsonPropertyName("track2")]
        public string? Track2 { get; set; }

        [JsonPropertyName("track3")]
        public string? Track3 { get; set; }

    }
}
