// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class NameValidationResultDto {
        [JsonPropertyName("errors")]
        public global::System.Collections.Generic.IList<NameValidationErrorReason>? Errors { get; set; }

        [JsonPropertyName("input")]
        public string? Input { get; set; }

        [JsonPropertyName("suggested")]
        public string? Suggested { get; set; }

        [JsonPropertyName("valid")]
        public bool? Valid { get; set; }

    }
}
