// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class OcrResultDto {
        [JsonPropertyName("durationMs")]
        public long? DurationMs { get; set; }

        [JsonPropertyName("meanConfidence")]
        public float? MeanConfidence { get; set; }

        [JsonPropertyName("text")]
        public string? Text { get; set; }

    }
}
