// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(OperationCategoryJsonConverter))]
    public enum OperationCategory {
        Perso,
        Inspection,
        Qa,
        Move,
        DocumentRecognition,
    }

    internal static class OperationCategoryExtensions {
        public static string ToWireValue(this OperationCategory value) {
            return value switch
            {
                OperationCategory.Perso => "Perso",
                OperationCategory.Inspection => "Inspection",
                OperationCategory.Qa => "Qa",
                OperationCategory.Move => "Move",
                OperationCategory.DocumentRecognition => "DocumentRecognition",
                _ => value.ToString(),
            };
        }

        public static OperationCategory ParseOperationCategory(this string value) {
            return value switch
            {
                "Perso" => OperationCategory.Perso,
                "Inspection" => OperationCategory.Inspection,
                "Qa" => OperationCategory.Qa,
                "Move" => OperationCategory.Move,
                "DocumentRecognition" => OperationCategory.DocumentRecognition,
                _ => throw new System.ArgumentException($"Unknown OperationCategory value: {value}"),
            };
        }
    }

    internal sealed class OperationCategoryJsonConverter : System.Text.Json.Serialization.JsonConverter<OperationCategory> {
        public override OperationCategory Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseOperationCategory();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, OperationCategory value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
