// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class OpticSettings {
        [JsonPropertyName("cameraPresetName")]
        public string? CameraPresetName { get; set; }

        [JsonPropertyName("pixelsPerMillimeterX")]
        public double? PixelsPerMillimeterX { get; set; }

        [JsonPropertyName("pixelsPerMillimeterY")]
        public double? PixelsPerMillimeterY { get; set; }

        [JsonPropertyName("warpPerspectiveOutputSizeX")]
        public double? WarpPerspectiveOutputSizeX { get; set; }

        [JsonPropertyName("warpPerspectiveOutputSizeY")]
        public double? WarpPerspectiveOutputSizeY { get; set; }

    }
}
