// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class PersonalizationSessionEventDto {
        [JsonPropertyName("message")]
        public string? Message { get; set; }

        [JsonPropertyName("recordId")]
        public int? RecordId { get; set; }

        [JsonPropertyName("success")]
        public bool? Success { get; set; }

        [JsonPropertyName("timestamp")]
        public global::System.DateTimeOffset? Timestamp { get; set; }

    }
}
