// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class PersoProcessConfigurationDto {
        [JsonPropertyName("feedSide")]
        public SupportSide? FeedSide { get; set; }

        [JsonPropertyName("inputFeeder")]
        public InputFeeders? InputFeeder { get; set; }

        [JsonPropertyName("readBack")]
        public ReadBackType? ReadBack { get; set; }

    }
}
