// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class PersoOperationDto {
        [JsonPropertyName("details")]
        public global::System.Collections.Generic.IList<string>? Details { get; set; }

        [JsonPropertyName("id")]
        public int? Id { get; set; }

        [JsonPropertyName("label")]
        public string? Label { get; set; }

        [JsonPropertyName("status")]
        public PersoOperationStatus? Status { get; set; }

        [JsonPropertyName("type")]
        public string? Type { get; set; }

    }
}
