// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class PixelMapDto {
        [JsonPropertyName("zone01")]
        public int? Zone01 { get; set; }

        [JsonPropertyName("zone02")]
        public int? Zone02 { get; set; }

        [JsonPropertyName("zone03")]
        public int? Zone03 { get; set; }

        [JsonPropertyName("zone04")]
        public int? Zone04 { get; set; }

        [JsonPropertyName("zone05")]
        public int? Zone05 { get; set; }

        [JsonPropertyName("zone06")]
        public int? Zone06 { get; set; }

    }
}
