// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class PrinterStateDto {
        [JsonPropertyName("doorsStatusFlags")]
        public XPrintDoorStatusFlags? DoorsStatusFlags { get; set; }

        [JsonPropertyName("firmware")]
        public string? Firmware { get; set; }

        [JsonPropertyName("headAxisMotorStatus")]
        public XPrintHeadAxisMotorStatus? HeadAxisMotorStatus { get; set; }

        [JsonPropertyName("mainSubSystemStatus")]
        public XPrintMainSubsystemStatus? MainSubSystemStatus { get; set; }

        [JsonPropertyName("mainSystemStatus")]
        public XPrintMainSystemStatus? MainSystemStatus { get; set; }

        [JsonPropertyName("positionsFlags")]
        public XPrintTransportAxisPositionFlags? PositionsFlags { get; set; }

        [JsonPropertyName("serialNumber")]
        public string? SerialNumber { get; set; }

        [JsonPropertyName("temperatureReadings")]
        public TemperatureReadingsDto? TemperatureReadings { get; set; }

        [JsonPropertyName("transportAxisMotorStatus")]
        public XPrintTransportAxisMotorStatus? TransportAxisMotorStatus { get; set; }

        [JsonPropertyName("vacuumPressureMillibar")]
        public float? VacuumPressureMillibar { get; set; }

        [JsonPropertyName("voltageReadings")]
        public VoltageReadingsDto? VoltageReadings { get; set; }

        [JsonPropertyName("xPrintHeadPosition")]
        public XPrintHeadAxisPositionFlags? XPrintHeadPosition { get; set; }

    }
}
