// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class PrintPatternRequest {
        [JsonPropertyName("direct")]
        public bool? Direct { get; set; }

        [JsonPropertyName("pattern")]
        public string? Pattern { get; set; }

        [JsonPropertyName("quality")]
        public PrintQuality Quality { get; set; }

    }
}
