// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class PropertyDto {
        [JsonPropertyName("description")]
        public string? Description { get; set; }

        [JsonPropertyName("devicePropertyType")]
        public DevicePropertyType? DevicePropertyType { get; set; }

        [JsonPropertyName("group")]
        public string? Group { get; set; }

        [JsonPropertyName("name")]
        public string? Name { get; set; }

        [JsonPropertyName("readOnly")]
        public bool? ReadOnly { get; set; }

        [JsonPropertyName("value")]
        public string? Value { get; set; }

    }
}
