// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class QueueItem {
        [JsonPropertyName("batchId")]
        public string? BatchId { get; set; }

        [JsonPropertyName("correlationId")]
        public string? CorrelationId { get; set; }

        [JsonPropertyName("id")]
        public int? Id { get; set; }

        [JsonPropertyName("jobStatus")]
        public JobStatus? JobStatus { get; set; }

        [JsonPropertyName("workflowInstanceId")]
        public string? WorkflowInstanceId { get; set; }

    }
}
