// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(ReadCartridgeServiceMemoryErrorCodesJsonConverter))]
    public enum ReadCartridgeServiceMemoryErrorCodes {
        NoError,
        PrinterBoardCommunicationError,
        CartridgeMissing,
        GenericError,
    }

    internal static class ReadCartridgeServiceMemoryErrorCodesExtensions {
        public static string ToWireValue(this ReadCartridgeServiceMemoryErrorCodes value) {
            return value switch
            {
                ReadCartridgeServiceMemoryErrorCodes.NoError => "NoError",
                ReadCartridgeServiceMemoryErrorCodes.PrinterBoardCommunicationError => "PrinterBoardCommunicationError",
                ReadCartridgeServiceMemoryErrorCodes.CartridgeMissing => "CartridgeMissing",
                ReadCartridgeServiceMemoryErrorCodes.GenericError => "GenericError",
                _ => value.ToString(),
            };
        }

        public static ReadCartridgeServiceMemoryErrorCodes ParseReadCartridgeServiceMemoryErrorCodes(this string value) {
            return value switch
            {
                "NoError" => ReadCartridgeServiceMemoryErrorCodes.NoError,
                "PrinterBoardCommunicationError" => ReadCartridgeServiceMemoryErrorCodes.PrinterBoardCommunicationError,
                "CartridgeMissing" => ReadCartridgeServiceMemoryErrorCodes.CartridgeMissing,
                "GenericError" => ReadCartridgeServiceMemoryErrorCodes.GenericError,
                _ => throw new System.ArgumentException($"Unknown ReadCartridgeServiceMemoryErrorCodes value: {value}"),
            };
        }
    }

    internal sealed class ReadCartridgeServiceMemoryErrorCodesJsonConverter : System.Text.Json.Serialization.JsonConverter<ReadCartridgeServiceMemoryErrorCodes> {
        public override ReadCartridgeServiceMemoryErrorCodes Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseReadCartridgeServiceMemoryErrorCodes();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, ReadCartridgeServiceMemoryErrorCodes value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
