// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class RuntimeOcrInspectionResult {
        [JsonPropertyName("inspectionName")]
        public string? InspectionName { get; set; }

        [JsonPropertyName("ocrResult")]
        public OcrResult? OcrResult { get; set; }

    }
}
