// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class ScannerMarkGroupDto {
        [JsonPropertyName("description")]
        public string? Description { get; set; }

        [JsonPropertyName("deviceId")]
        public string? DeviceId { get; set; }

        [JsonPropertyName("displayName")]
        public string? DisplayName { get; set; }

        [JsonPropertyName("entities")]
        public global::System.Collections.Generic.IList<MarkGroupScannerEntityDto>? Entities { get; set; }

        [JsonPropertyName("expectedMarkDuration")]
        public string? ExpectedMarkDuration { get; set; }

        [JsonPropertyName("id")]
        public int? Id { get; set; }

        [JsonPropertyName("index")]
        public int? Index { get; set; }

        [JsonPropertyName("jobTemplateId")]
        public int? JobTemplateId { get; set; }

        [JsonPropertyName("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The target position the support should be in
        /// when marking entities
        /// </summary>
        [JsonPropertyName("positionId")]
        public string? PositionId { get; set; }

        /// <summary>
        /// The scanner module that will mark entities
        /// </summary>
        [JsonPropertyName("scannerId")]
        public string? ScannerId { get; set; }

        [JsonPropertyName("supportSide")]
        public string? SupportSide { get; set; }

    }
}
