// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(SCardDispositionJsonConverter))]
    public enum SCardDisposition {
        LeaveCard,
        ResetCard,
        UnpowerCard,
        EjectCard,
    }

    internal static class SCardDispositionExtensions {
        public static string ToWireValue(this SCardDisposition value) {
            return value switch
            {
                SCardDisposition.LeaveCard => "LeaveCard",
                SCardDisposition.ResetCard => "ResetCard",
                SCardDisposition.UnpowerCard => "UnpowerCard",
                SCardDisposition.EjectCard => "EjectCard",
                _ => value.ToString(),
            };
        }

        public static SCardDisposition ParseSCardDisposition(this string value) {
            return value switch
            {
                "LeaveCard" => SCardDisposition.LeaveCard,
                "ResetCard" => SCardDisposition.ResetCard,
                "UnpowerCard" => SCardDisposition.UnpowerCard,
                "EjectCard" => SCardDisposition.EjectCard,
                _ => throw new System.ArgumentException($"Unknown SCardDisposition value: {value}"),
            };
        }
    }

    internal sealed class SCardDispositionJsonConverter : System.Text.Json.Serialization.JsonConverter<SCardDisposition> {
        public override SCardDisposition Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseSCardDisposition();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, SCardDisposition value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
