// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class SCardConnectParamsDto {
        [JsonPropertyName("preferredProtocol")]
        public SCardProtocol? PreferredProtocol { get; set; }

        [JsonPropertyName("share")]
        public SCardShare? Share { get; set; }

    }
}
