// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(SCardProtocolJsonConverter))]
    public enum SCardProtocol {
        Undefined,
        T0,
        T1,
        Any,
        Default,
    }

    internal static class SCardProtocolExtensions {
        public static string ToWireValue(this SCardProtocol value) {
            return value switch
            {
                SCardProtocol.Undefined => "Undefined",
                SCardProtocol.T0 => "T0",
                SCardProtocol.T1 => "T1",
                SCardProtocol.Any => "Any",
                SCardProtocol.Default => "Default",
                _ => value.ToString(),
            };
        }

        public static SCardProtocol ParseSCardProtocol(this string value) {
            return value switch
            {
                "Undefined" => SCardProtocol.Undefined,
                "T0" => SCardProtocol.T0,
                "T1" => SCardProtocol.T1,
                "Any" => SCardProtocol.Any,
                "Default" => SCardProtocol.Default,
                _ => throw new System.ArgumentException($"Unknown SCardProtocol value: {value}"),
            };
        }
    }

    internal sealed class SCardProtocolJsonConverter : System.Text.Json.Serialization.JsonConverter<SCardProtocol> {
        public override SCardProtocol Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseSCardProtocol();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, SCardProtocol value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
