// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(SCardReaderStateJsonConverter))]
    public enum SCardReaderState {
        Unaware,
        Ignore,
        Changed,
        Unknown,
        Unavailable,
        Empty,
        Present,
        AtrMatch,
        Exclusive,
        InUse,
        Mute,
        Unpowered,
    }

    internal static class SCardReaderStateExtensions {
        public static string ToWireValue(this SCardReaderState value) {
            return value switch
            {
                SCardReaderState.Unaware => "Unaware",
                SCardReaderState.Ignore => "Ignore",
                SCardReaderState.Changed => "Changed",
                SCardReaderState.Unknown => "Unknown",
                SCardReaderState.Unavailable => "Unavailable",
                SCardReaderState.Empty => "Empty",
                SCardReaderState.Present => "Present",
                SCardReaderState.AtrMatch => "AtrMatch",
                SCardReaderState.Exclusive => "Exclusive",
                SCardReaderState.InUse => "InUse",
                SCardReaderState.Mute => "Mute",
                SCardReaderState.Unpowered => "Unpowered",
                _ => value.ToString(),
            };
        }

        public static SCardReaderState ParseSCardReaderState(this string value) {
            return value switch
            {
                "Unaware" => SCardReaderState.Unaware,
                "Ignore" => SCardReaderState.Ignore,
                "Changed" => SCardReaderState.Changed,
                "Unknown" => SCardReaderState.Unknown,
                "Unavailable" => SCardReaderState.Unavailable,
                "Empty" => SCardReaderState.Empty,
                "Present" => SCardReaderState.Present,
                "AtrMatch" => SCardReaderState.AtrMatch,
                "Exclusive" => SCardReaderState.Exclusive,
                "InUse" => SCardReaderState.InUse,
                "Mute" => SCardReaderState.Mute,
                "Unpowered" => SCardReaderState.Unpowered,
                _ => throw new System.ArgumentException($"Unknown SCardReaderState value: {value}"),
            };
        }
    }

    internal sealed class SCardReaderStateJsonConverter : System.Text.Json.Serialization.JsonConverter<SCardReaderState> {
        public override SCardReaderState Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseSCardReaderState();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, SCardReaderState value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
