// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(SecurityFeatureKindJsonConverter))]
    public enum SecurityFeatureKind {
        None,
        Cli,
        Mli,
    }

    internal static class SecurityFeatureKindExtensions {
        public static string ToWireValue(this SecurityFeatureKind value) {
            return value switch
            {
                SecurityFeatureKind.None => "None",
                SecurityFeatureKind.Cli => "Cli",
                SecurityFeatureKind.Mli => "Mli",
                _ => value.ToString(),
            };
        }

        public static SecurityFeatureKind ParseSecurityFeatureKind(this string value) {
            return value switch
            {
                "None" => SecurityFeatureKind.None,
                "Cli" => SecurityFeatureKind.Cli,
                "Mli" => SecurityFeatureKind.Mli,
                _ => throw new System.ArgumentException($"Unknown SecurityFeatureKind value: {value}"),
            };
        }
    }

    internal sealed class SecurityFeatureKindJsonConverter : System.Text.Json.Serialization.JsonConverter<SecurityFeatureKind> {
        public override SecurityFeatureKind Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseSecurityFeatureKind();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, SecurityFeatureKind value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
