// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class SmartCardReaderState {
        [JsonPropertyName("currentState")]
        public SCardReaderState? CurrentState { get; set; }

        [JsonPropertyName("readerName")]
        public string? ReaderName { get; set; }

        [JsonPropertyName("updateCount")]
        public int? UpdateCount { get; set; }

    }
}
