// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class SystemStatusDto {
        [JsonPropertyName("errors")]
        public global::System.Collections.Generic.IList<SystemErrorCodes>? Errors { get; set; }

        [JsonPropertyName("status")]
        public SystemStatus? Status { get; set; }

    }
}
