// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class TemperatureReadingsDto {
        [JsonPropertyName("board1TemperatureCelsius")]
        public float? Board1TemperatureCelsius { get; set; }

        [JsonPropertyName("board2TemperatureCelsius")]
        public float? Board2TemperatureCelsius { get; set; }

        [JsonPropertyName("heaterTemperatureCelsius")]
        public float? HeaterTemperatureCelsius { get; set; }

        [JsonPropertyName("internalTemperatureCelsius")]
        public float? InternalTemperatureCelsius { get; set; }

        [JsonPropertyName("printHeadTemperatureCelsius")]
        public float? PrintHeadTemperatureCelsius { get; set; }

    }
}
