// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class TemplateMatchingConfiguration {
        [JsonPropertyName("acquisitionPresetName")]
        public string? AcquisitionPresetName { get; set; }

        [JsonPropertyName("cameraId")]
        public string? CameraId { get; set; }

        [JsonPropertyName("createdAt")]
        public global::System.DateTimeOffset? CreatedAt { get; set; }

        [JsonPropertyName("description")]
        public string? Description { get; set; }

        [JsonPropertyName("displayName")]
        public string? DisplayName { get; set; }

        [JsonPropertyName("id")]
        public int? Id { get; set; }

        [JsonPropertyName("illuminationEnabled")]
        public bool? IlluminationEnabled { get; set; }

        [JsonPropertyName("isConfigured")]
        public bool? IsConfigured { get; set; }

        [JsonPropertyName("name")]
        public string? Name { get; set; }

        [JsonPropertyName("scannerId")]
        public string? ScannerId { get; set; }

        [JsonPropertyName("searchArea")]
        public Rectangle? SearchArea { get; set; }

        [JsonPropertyName("searchPatternImage")]
        public ApplicationImage? SearchPatternImage { get; set; }

        [JsonPropertyName("searchPatternImageId")]
        public int? SearchPatternImageId { get; set; }

        [JsonPropertyName("templateArea")]
        public Rectangle? TemplateArea { get; set; }

        [JsonPropertyName("threshold")]
        public float? Threshold { get; set; }

        [JsonPropertyName("updatedAt")]
        public global::System.DateTimeOffset? UpdatedAt { get; set; }

        [JsonPropertyName("warpPerspective")]
        public bool? WarpPerspective { get; set; }

    }
}
