// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(ToggleDeviceModeJsonConverter))]
    public enum ToggleDeviceMode {
        On,
        Off,
    }

    internal static class ToggleDeviceModeExtensions {
        public static string ToWireValue(this ToggleDeviceMode value) {
            return value switch
            {
                ToggleDeviceMode.On => "On",
                ToggleDeviceMode.Off => "Off",
                _ => value.ToString(),
            };
        }

        public static ToggleDeviceMode ParseToggleDeviceMode(this string value) {
            return value switch
            {
                "On" => ToggleDeviceMode.On,
                "Off" => ToggleDeviceMode.Off,
                _ => throw new System.ArgumentException($"Unknown ToggleDeviceMode value: {value}"),
            };
        }
    }

    internal sealed class ToggleDeviceModeJsonConverter : System.Text.Json.Serialization.JsonConverter<ToggleDeviceMode> {
        public override ToggleDeviceMode Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseToggleDeviceMode();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, ToggleDeviceMode value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
