// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class TransformOptions {
        [JsonPropertyName("mirrorX")]
        public bool? MirrorX { get; set; }

        [JsonPropertyName("mirrorY")]
        public bool? MirrorY { get; set; }

    }
}
