// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class TransportPosition {
        [JsonPropertyName("aliases")]
        public global::System.Collections.Generic.IList<TransportPosition>? Aliases { get; set; }

        [JsonPropertyName("connections")]
        public global::System.Collections.Generic.IList<TransportPosition>? Connections { get; set; }

        [JsonPropertyName("currentSupport")]
        public Support? CurrentSupport { get; set; }

        [JsonPropertyName("id")]
        public string? Id { get; set; }

        [JsonPropertyName("isAlias")]
        public bool? IsAlias { get; set; }

        [JsonPropertyName("isFeeder")]
        public bool? IsFeeder { get; set; }

        [JsonPropertyName("isFlip")]
        public bool? IsFlip { get; set; }

        [JsonPropertyName("isIntersection")]
        public bool? IsIntersection { get; set; }

        [JsonPropertyName("isMachineExit")]
        public bool? IsMachineExit { get; set; }

        [JsonPropertyName("isMachineInput")]
        public bool? IsMachineInput { get; set; }

        [JsonPropertyName("isMultiChipExit")]
        public bool? IsMultiChipExit { get; set; }

        [JsonPropertyName("isReject")]
        public bool? IsReject { get; set; }

        [JsonPropertyName("isTransient")]
        public bool? IsTransient { get; set; }

        [JsonPropertyName("moduleId")]
        public int? ModuleId { get; set; }

        [JsonPropertyName("occupied")]
        public bool? Occupied { get; set; }

        [JsonPropertyName("positionName")]
        public string? PositionName { get; set; }

        [JsonPropertyName("realPosition")]
        public string? RealPosition { get; set; }

        [JsonPropertyName("transportPositionType")]
        public TransportPositionType? TransportPositionType { get; set; }

    }
}
