// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class TransportModuleState {
        [JsonPropertyName("configuration")]
        public TransportModuleConfiguration? Configuration { get; set; }

        [JsonPropertyName("moduleId")]
        public int? ModuleId { get; set; }

        [JsonPropertyName("moduleStatus")]
        public TransportModuleStatus? ModuleStatus { get; set; }

        [JsonPropertyName("moduleType")]
        public TransportModuleType? ModuleType { get; set; }

        [JsonPropertyName("photoSensors")]
        public global::System.Collections.Generic.IList<PhotoSensor>? PhotoSensors { get; set; }

        [JsonPropertyName("serialNumber")]
        public string? SerialNumber { get; set; }

    }
}
