// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(TransportModuleTypeJsonConverter))]
    public enum TransportModuleType {
        MultiEncoder,
        MagneticStripeEncoder,
        Transport,
    }

    internal static class TransportModuleTypeExtensions {
        public static string ToWireValue(this TransportModuleType value) {
            return value switch
            {
                TransportModuleType.MultiEncoder => "MultiEncoder",
                TransportModuleType.MagneticStripeEncoder => "MagneticStripeEncoder",
                TransportModuleType.Transport => "Transport",
                _ => value.ToString(),
            };
        }

        public static TransportModuleType ParseTransportModuleType(this string value) {
            return value switch
            {
                "MultiEncoder" => TransportModuleType.MultiEncoder,
                "MagneticStripeEncoder" => TransportModuleType.MagneticStripeEncoder,
                "Transport" => TransportModuleType.Transport,
                _ => throw new System.ArgumentException($"Unknown TransportModuleType value: {value}"),
            };
        }
    }

    internal sealed class TransportModuleTypeJsonConverter : System.Text.Json.Serialization.JsonConverter<TransportModuleType> {
        public override TransportModuleType Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseTransportModuleType();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, TransportModuleType value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
