// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class UploadLayoutAndAddToJobTemplateRequest {
        [JsonPropertyName("files")]
        public global::System.Collections.Generic.IList<FormFile>? Files { get; set; }

    }
}
