// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class VoltageReadingsDto {
        [JsonPropertyName("feedbackVoltage12")]
        public float? FeedbackVoltage12 { get; set; }

        [JsonPropertyName("feedbackVoltage24")]
        public float? FeedbackVoltage24 { get; set; }

        [JsonPropertyName("feedbackVoltage48")]
        public float? FeedbackVoltage48 { get; set; }

    }
}
