// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(WorkflowMessageJsonConverter))]
    public partial class WorkflowMessage {
        [JsonPropertyName("additionalMetadata")]
        public global::System.Collections.Generic.IDictionary<string, object>? AdditionalMetadata { get; set; }

        [JsonPropertyName("batchId")]
        public string? BatchId { get; set; }

        [JsonPropertyName("correlationId")]
        public string? CorrelationId { get; set; }

        [JsonPropertyName("destructiveOperationExecuted")]
        public bool? DestructiveOperationExecuted { get; set; }

        [JsonPropertyName("discriminator")]
        public string? Discriminator { get; set; }

        [JsonPropertyName("documentProduced")]
        public bool? DocumentProduced { get; set; }

        [JsonPropertyName("errorCode")]
        public JobErrorCodes? ErrorCode { get; set; }

        [JsonPropertyName("hostName")]
        public string? HostName { get; set; }

        [JsonPropertyName("jobId")]
        public string? JobId { get; set; }

        [JsonPropertyName("jobStatus")]
        public JobStatus? JobStatus { get; set; }

        [JsonPropertyName("machineName")]
        public string? MachineName { get; set; }

        [JsonPropertyName("machineSerial")]
        public string? MachineSerial { get; set; }

        [JsonPropertyName("messageId")]
        public string? MessageId { get; set; }

        [JsonPropertyName("messageType")]
        public MessageType? MessageType { get; set; }

        [JsonPropertyName("sourceJobInstanceId")]
        public string? SourceJobInstanceId { get; set; }

        [JsonPropertyName("workflowInstanceId")]
        public string? WorkflowInstanceId { get; set; }

        [JsonPropertyName("workflowInstanceName")]
        public string? WorkflowInstanceName { get; set; }

    }

    internal sealed class WorkflowMessageJsonConverter : System.Text.Json.Serialization.JsonConverter<WorkflowMessage> {
        public override WorkflowMessage? Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            using var doc = System.Text.Json.JsonDocument.ParseValue(ref reader);
            var raw = doc.RootElement.GetRawText();

            if (doc.RootElement.TryGetProperty("discriminator", out var __disc))
            {
                switch (__disc.GetString())
                {
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.ChipReadBackMessage": return System.Text.Json.JsonSerializer.Deserialize<ChipReadBackMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.EncoderLoadedMessage": return System.Text.Json.JsonSerializer.Deserialize<EncoderLoadedMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.FeederEmptyMessage": return System.Text.Json.JsonSerializer.Deserialize<FeederEmptyMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.MagneticStripeReadBackMessage": return System.Text.Json.JsonSerializer.Deserialize<MagneticStripeReadBackMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.OcrExecutedMessage": return System.Text.Json.JsonSerializer.Deserialize<OcrExecutedMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.OcrReadBackMessage": return System.Text.Json.JsonSerializer.Deserialize<OcrReadBackMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.WebhookReceiverHealthCheckMessage": return System.Text.Json.JsonSerializer.Deserialize<WebhookReceiverHealthCheckMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.WorkflowCancelledMessage": return System.Text.Json.JsonSerializer.Deserialize<WorkflowCancelledMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.WorkflowCompletedMessage": return System.Text.Json.JsonSerializer.Deserialize<WorkflowCompletedMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.WorkflowFaultedMessage": return System.Text.Json.JsonSerializer.Deserialize<WorkflowFaultedMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.WorkflowSchedulerProcessSuspendedMessage": return System.Text.Json.JsonSerializer.Deserialize<WorkflowSchedulerProcessSuspendedMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.WorkflowSchedulerStartedMessage": return System.Text.Json.JsonSerializer.Deserialize<WorkflowSchedulerStartedMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.WorkflowSchedulerStoppedMessage": return System.Text.Json.JsonSerializer.Deserialize<WorkflowSchedulerStoppedMessage>(raw, options);
                    case "IXLA.Box.Services.Workflow.Messaging.Signals.WorkflowStartedMessage": return System.Text.Json.JsonSerializer.Deserialize<WorkflowStartedMessage>(raw, options);
                }
            }

            return System.Text.Json.JsonSerializer.Deserialize<
                WorkflowMessage>(raw, WithoutSelf(options));
        }

        public override void Write(System.Text.Json.Utf8JsonWriter writer, WorkflowMessage value, System.Text.Json.JsonSerializerOptions options) {
            var type = value.GetType();
            if (type == typeof(WorkflowMessage))
            {
                System.Text.Json.JsonSerializer.Serialize(writer, value, WithoutSelf(options));
            }
            else
            {
                System.Text.Json.JsonSerializer.Serialize(writer, value, type, options);
            }
        }

        private System.Text.Json.JsonSerializerOptions? _noSelf;

        private System.Text.Json.JsonSerializerOptions WithoutSelf(System.Text.Json.JsonSerializerOptions source) {
            if (_noSelf is not null) return _noSelf;
            var copy = new System.Text.Json.JsonSerializerOptions(source);
            for (int i = copy.Converters.Count - 1; i >= 0; i--)
            {
                if (copy.Converters[i] is WorkflowMessageJsonConverter) copy.Converters.RemoveAt(i);
            }
            _noSelf = copy;
            return copy;
        }
    }
}
