// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(WorkflowSchedulerStatusJsonConverter))]
    public enum WorkflowSchedulerStatus {
        Starting,
        Running,
        Waiting,
        Error,
        Stopping,
        Stopped,
        FeederEmpty,
        JobQueueEmpty,
    }

    internal static class WorkflowSchedulerStatusExtensions {
        public static string ToWireValue(this WorkflowSchedulerStatus value) {
            return value switch
            {
                WorkflowSchedulerStatus.Starting => "Starting",
                WorkflowSchedulerStatus.Running => "Running",
                WorkflowSchedulerStatus.Waiting => "Waiting",
                WorkflowSchedulerStatus.Error => "Error",
                WorkflowSchedulerStatus.Stopping => "Stopping",
                WorkflowSchedulerStatus.Stopped => "Stopped",
                WorkflowSchedulerStatus.FeederEmpty => "FeederEmpty",
                WorkflowSchedulerStatus.JobQueueEmpty => "JobQueueEmpty",
                _ => value.ToString(),
            };
        }

        public static WorkflowSchedulerStatus ParseWorkflowSchedulerStatus(this string value) {
            return value switch
            {
                "Starting" => WorkflowSchedulerStatus.Starting,
                "Running" => WorkflowSchedulerStatus.Running,
                "Waiting" => WorkflowSchedulerStatus.Waiting,
                "Error" => WorkflowSchedulerStatus.Error,
                "Stopping" => WorkflowSchedulerStatus.Stopping,
                "Stopped" => WorkflowSchedulerStatus.Stopped,
                "FeederEmpty" => WorkflowSchedulerStatus.FeederEmpty,
                "JobQueueEmpty" => WorkflowSchedulerStatus.JobQueueEmpty,
                _ => throw new System.ArgumentException($"Unknown WorkflowSchedulerStatus value: {value}"),
            };
        }
    }

    internal sealed class WorkflowSchedulerStatusJsonConverter : System.Text.Json.Serialization.JsonConverter<WorkflowSchedulerStatus> {
        public override WorkflowSchedulerStatus Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseWorkflowSchedulerStatus();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, WorkflowSchedulerStatus value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
