// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(WorkflowSchedulerErrorCodesJsonConverter))]
    public enum WorkflowSchedulerErrorCodes {
        JobTemplateDoesNotExists,
        InvalidDataSourceConfiguration,
        WebhooksServerUnreachable,
        TransportResetFailed,
        FeederEmpty,
        InvalidWorkflowTypeName,
    }

    internal static class WorkflowSchedulerErrorCodesExtensions {
        public static string ToWireValue(this WorkflowSchedulerErrorCodes value) {
            return value switch
            {
                WorkflowSchedulerErrorCodes.JobTemplateDoesNotExists => "JobTemplateDoesNotExists",
                WorkflowSchedulerErrorCodes.InvalidDataSourceConfiguration => "InvalidDataSourceConfiguration",
                WorkflowSchedulerErrorCodes.WebhooksServerUnreachable => "WebhooksServerUnreachable",
                WorkflowSchedulerErrorCodes.TransportResetFailed => "TransportResetFailed",
                WorkflowSchedulerErrorCodes.FeederEmpty => "FeederEmpty",
                WorkflowSchedulerErrorCodes.InvalidWorkflowTypeName => "InvalidWorkflowTypeName",
                _ => value.ToString(),
            };
        }

        public static WorkflowSchedulerErrorCodes ParseWorkflowSchedulerErrorCodes(this string value) {
            return value switch
            {
                "JobTemplateDoesNotExists" => WorkflowSchedulerErrorCodes.JobTemplateDoesNotExists,
                "InvalidDataSourceConfiguration" => WorkflowSchedulerErrorCodes.InvalidDataSourceConfiguration,
                "WebhooksServerUnreachable" => WorkflowSchedulerErrorCodes.WebhooksServerUnreachable,
                "TransportResetFailed" => WorkflowSchedulerErrorCodes.TransportResetFailed,
                "FeederEmpty" => WorkflowSchedulerErrorCodes.FeederEmpty,
                "InvalidWorkflowTypeName" => WorkflowSchedulerErrorCodes.InvalidWorkflowTypeName,
                _ => throw new System.ArgumentException($"Unknown WorkflowSchedulerErrorCodes value: {value}"),
            };
        }
    }

    internal sealed class WorkflowSchedulerErrorCodesJsonConverter : System.Text.Json.Serialization.JsonConverter<WorkflowSchedulerErrorCodes> {
        public override WorkflowSchedulerErrorCodes Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseWorkflowSchedulerErrorCodes();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, WorkflowSchedulerErrorCodes value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
