// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class WorkflowInstanceStateChangedEventArgs {
        [JsonPropertyName("currentPositionId")]
        public string? CurrentPositionId { get; set; }

        [JsonPropertyName("executingActivityId")]
        public string? ExecutingActivityId { get; set; }

        [JsonPropertyName("executingActivityName")]
        public string? ExecutingActivityName { get; set; }

        [JsonPropertyName("lastExecutedActivityId")]
        public string? LastExecutedActivityId { get; set; }

        [JsonPropertyName("lastExecutedActivityName")]
        public string? LastExecutedActivityName { get; set; }

        [JsonPropertyName("status")]
        public WorkflowStatus? Status { get; set; }

        [JsonPropertyName("supportId")]
        public string? SupportId { get; set; }

        [JsonPropertyName("workflowInstanceId")]
        public string? WorkflowInstanceId { get; set; }

    }
}
