// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class WorkflowSchedulerStateDto {
        [JsonPropertyName("currentJobTemplateId")]
        public int? CurrentJobTemplateId { get; set; }

        [JsonPropertyName("currentJobTemplateName")]
        public string? CurrentJobTemplateName { get; set; }

        [JsonPropertyName("errorDetails")]
        public string? ErrorDetails { get; set; }

        [JsonPropertyName("errors")]
        public global::System.Collections.Generic.IList<WorkflowSchedulerErrorCodes>? Errors { get; set; }

        [JsonPropertyName("lastLoadedItemId")]
        public int? LastLoadedItemId { get; set; }

        [JsonPropertyName("queueSize")]
        public int? QueueSize { get; set; }

        [JsonPropertyName("queuedOrderIds")]
        public global::System.Collections.Generic.IList<int>? QueuedOrderIds { get; set; }

        [JsonPropertyName("sessionId")]
        public string? SessionId { get; set; }

        [JsonPropertyName("startupParameters")]
        public WorkflowSchedulerStartupParamsDto? StartupParameters { get; set; }

        [JsonPropertyName("status")]
        public WorkflowSchedulerStatus? Status { get; set; }

        [JsonPropertyName("stopReason")]
        public WorkflowSchedulerStopReason? StopReason { get; set; }

        [JsonPropertyName("stopSourceJobId")]
        public string? StopSourceJobId { get; set; }

        [JsonPropertyName("upTimeSeconds")]
        public int? UpTimeSeconds { get; set; }

        [JsonPropertyName("workflowTypeName")]
        public string? WorkflowTypeName { get; set; }

    }
}
