// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    public partial class WriteUInt16Request {
        [JsonPropertyName("address")]
        public int Address { get; set; }

        [JsonPropertyName("slaveId")]
        public int SlaveId { get; set; }

        [JsonPropertyName("value")]
        public int Value { get; set; }

    }
}
