// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(XpOneMainStatusJsonConverter))]
    public enum XpOneMainStatus {
        StInit,
        StWaitInsertion,
        StReadyToStart,
        StReadyForPerso,
        StPersoRunning,
        StProcessFinished,
        StShutdownRequest,
        StError,
    }

    internal static class XpOneMainStatusExtensions {
        public static string ToWireValue(this XpOneMainStatus value) {
            return value switch
            {
                XpOneMainStatus.StInit => "StInit",
                XpOneMainStatus.StWaitInsertion => "StWaitInsertion",
                XpOneMainStatus.StReadyToStart => "StReadyToStart",
                XpOneMainStatus.StReadyForPerso => "StReadyForPerso",
                XpOneMainStatus.StPersoRunning => "StPersoRunning",
                XpOneMainStatus.StProcessFinished => "StProcessFinished",
                XpOneMainStatus.StShutdownRequest => "StShutdownRequest",
                XpOneMainStatus.StError => "StError",
                _ => value.ToString(),
            };
        }

        public static XpOneMainStatus ParseXpOneMainStatus(this string value) {
            return value switch
            {
                "StInit" => XpOneMainStatus.StInit,
                "StWaitInsertion" => XpOneMainStatus.StWaitInsertion,
                "StReadyToStart" => XpOneMainStatus.StReadyToStart,
                "StReadyForPerso" => XpOneMainStatus.StReadyForPerso,
                "StPersoRunning" => XpOneMainStatus.StPersoRunning,
                "StProcessFinished" => XpOneMainStatus.StProcessFinished,
                "StShutdownRequest" => XpOneMainStatus.StShutdownRequest,
                "StError" => XpOneMainStatus.StError,
                _ => throw new System.ArgumentException($"Unknown XpOneMainStatus value: {value}"),
            };
        }
    }

    internal sealed class XpOneMainStatusJsonConverter : System.Text.Json.Serialization.JsonConverter<XpOneMainStatus> {
        public override XpOneMainStatus Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseXpOneMainStatus();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, XpOneMainStatus value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
