// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(XpOneMainSubsystemStatusJsonConverter))]
    public enum XpOneMainSubsystemStatus {
        NoErr,
        TemperatureErr,
        ApplErr,
        PwrsplyErr,
    }

    internal static class XpOneMainSubsystemStatusExtensions {
        public static string ToWireValue(this XpOneMainSubsystemStatus value) {
            return value switch
            {
                XpOneMainSubsystemStatus.NoErr => "NoErr",
                XpOneMainSubsystemStatus.TemperatureErr => "TemperatureErr",
                XpOneMainSubsystemStatus.ApplErr => "ApplErr",
                XpOneMainSubsystemStatus.PwrsplyErr => "PwrsplyErr",
                _ => value.ToString(),
            };
        }

        public static XpOneMainSubsystemStatus ParseXpOneMainSubsystemStatus(this string value) {
            return value switch
            {
                "NoErr" => XpOneMainSubsystemStatus.NoErr,
                "TemperatureErr" => XpOneMainSubsystemStatus.TemperatureErr,
                "ApplErr" => XpOneMainSubsystemStatus.ApplErr,
                "PwrsplyErr" => XpOneMainSubsystemStatus.PwrsplyErr,
                _ => throw new System.ArgumentException($"Unknown XpOneMainSubsystemStatus value: {value}"),
            };
        }
    }

    internal sealed class XpOneMainSubsystemStatusJsonConverter : System.Text.Json.Serialization.JsonConverter<XpOneMainSubsystemStatus> {
        public override XpOneMainSubsystemStatus Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseXpOneMainSubsystemStatus();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, XpOneMainSubsystemStatus value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
