// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(XPrintMainSubsystemStatusJsonConverter))]
    public enum XPrintMainSubsystemStatus {
        NoErrors,
        TransportAxisError,
        HeadAxisError,
        CappingError,
        UvLampError,
        FumExtractorError,
        TemperatureError,
        CartridgesError,
        ApplicationError,
        PowerSupplyError,
        ResetRequired,
    }

    internal static class XPrintMainSubsystemStatusExtensions {
        public static string ToWireValue(this XPrintMainSubsystemStatus value) {
            return value switch
            {
                XPrintMainSubsystemStatus.NoErrors => "NoErrors",
                XPrintMainSubsystemStatus.TransportAxisError => "TransportAxisError",
                XPrintMainSubsystemStatus.HeadAxisError => "HeadAxisError",
                XPrintMainSubsystemStatus.CappingError => "CappingError",
                XPrintMainSubsystemStatus.UvLampError => "UvLampError",
                XPrintMainSubsystemStatus.FumExtractorError => "FumExtractorError",
                XPrintMainSubsystemStatus.TemperatureError => "TemperatureError",
                XPrintMainSubsystemStatus.CartridgesError => "CartridgesError",
                XPrintMainSubsystemStatus.ApplicationError => "ApplicationError",
                XPrintMainSubsystemStatus.PowerSupplyError => "PowerSupplyError",
                XPrintMainSubsystemStatus.ResetRequired => "ResetRequired",
                _ => value.ToString(),
            };
        }

        public static XPrintMainSubsystemStatus ParseXPrintMainSubsystemStatus(this string value) {
            return value switch
            {
                "NoErrors" => XPrintMainSubsystemStatus.NoErrors,
                "TransportAxisError" => XPrintMainSubsystemStatus.TransportAxisError,
                "HeadAxisError" => XPrintMainSubsystemStatus.HeadAxisError,
                "CappingError" => XPrintMainSubsystemStatus.CappingError,
                "UvLampError" => XPrintMainSubsystemStatus.UvLampError,
                "FumExtractorError" => XPrintMainSubsystemStatus.FumExtractorError,
                "TemperatureError" => XPrintMainSubsystemStatus.TemperatureError,
                "CartridgesError" => XPrintMainSubsystemStatus.CartridgesError,
                "ApplicationError" => XPrintMainSubsystemStatus.ApplicationError,
                "PowerSupplyError" => XPrintMainSubsystemStatus.PowerSupplyError,
                "ResetRequired" => XPrintMainSubsystemStatus.ResetRequired,
                _ => throw new System.ArgumentException($"Unknown XPrintMainSubsystemStatus value: {value}"),
            };
        }
    }

    internal sealed class XPrintMainSubsystemStatusJsonConverter : System.Text.Json.Serialization.JsonConverter<XPrintMainSubsystemStatus> {
        public override XPrintMainSubsystemStatus Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseXPrintMainSubsystemStatus();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, XPrintMainSubsystemStatus value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
