// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(XPrintDoorStatusFlagsJsonConverter))]
    public enum XPrintDoorStatusFlags {
        AllClosed,
        FrontRight,
        FrontLeft,
        RearLeft,
        InspectionDoor,
        AnyInterlock,
        ExternalInterlock,
    }

    internal static class XPrintDoorStatusFlagsExtensions {
        public static string ToWireValue(this XPrintDoorStatusFlags value) {
            return value switch
            {
                XPrintDoorStatusFlags.AllClosed => "AllClosed",
                XPrintDoorStatusFlags.FrontRight => "FrontRight",
                XPrintDoorStatusFlags.FrontLeft => "FrontLeft",
                XPrintDoorStatusFlags.RearLeft => "RearLeft",
                XPrintDoorStatusFlags.InspectionDoor => "InspectionDoor",
                XPrintDoorStatusFlags.AnyInterlock => "AnyInterlock",
                XPrintDoorStatusFlags.ExternalInterlock => "ExternalInterlock",
                _ => value.ToString(),
            };
        }

        public static XPrintDoorStatusFlags ParseXPrintDoorStatusFlags(this string value) {
            return value switch
            {
                "AllClosed" => XPrintDoorStatusFlags.AllClosed,
                "FrontRight" => XPrintDoorStatusFlags.FrontRight,
                "FrontLeft" => XPrintDoorStatusFlags.FrontLeft,
                "RearLeft" => XPrintDoorStatusFlags.RearLeft,
                "InspectionDoor" => XPrintDoorStatusFlags.InspectionDoor,
                "AnyInterlock" => XPrintDoorStatusFlags.AnyInterlock,
                "ExternalInterlock" => XPrintDoorStatusFlags.ExternalInterlock,
                _ => throw new System.ArgumentException($"Unknown XPrintDoorStatusFlags value: {value}"),
            };
        }
    }

    internal sealed class XPrintDoorStatusFlagsJsonConverter : System.Text.Json.Serialization.JsonConverter<XPrintDoorStatusFlags> {
        public override XPrintDoorStatusFlags Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseXPrintDoorStatusFlags();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, XPrintDoorStatusFlags value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
