// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(XPrintMainSystemStatusJsonConverter))]
    public enum XPrintMainSystemStatus {
        Ready,
        FeederEmpty,
        Error,
        PassportDestinationFull,
        EmergencyStop,
        ResetRequired,
        Busy,
    }

    internal static class XPrintMainSystemStatusExtensions {
        public static string ToWireValue(this XPrintMainSystemStatus value) {
            return value switch
            {
                XPrintMainSystemStatus.Ready => "Ready",
                XPrintMainSystemStatus.FeederEmpty => "FeederEmpty",
                XPrintMainSystemStatus.Error => "Error",
                XPrintMainSystemStatus.PassportDestinationFull => "PassportDestinationFull",
                XPrintMainSystemStatus.EmergencyStop => "EmergencyStop",
                XPrintMainSystemStatus.ResetRequired => "ResetRequired",
                XPrintMainSystemStatus.Busy => "Busy",
                _ => value.ToString(),
            };
        }

        public static XPrintMainSystemStatus ParseXPrintMainSystemStatus(this string value) {
            return value switch
            {
                "Ready" => XPrintMainSystemStatus.Ready,
                "FeederEmpty" => XPrintMainSystemStatus.FeederEmpty,
                "Error" => XPrintMainSystemStatus.Error,
                "PassportDestinationFull" => XPrintMainSystemStatus.PassportDestinationFull,
                "EmergencyStop" => XPrintMainSystemStatus.EmergencyStop,
                "ResetRequired" => XPrintMainSystemStatus.ResetRequired,
                "Busy" => XPrintMainSystemStatus.Busy,
                _ => throw new System.ArgumentException($"Unknown XPrintMainSystemStatus value: {value}"),
            };
        }
    }

    internal sealed class XPrintMainSystemStatusJsonConverter : System.Text.Json.Serialization.JsonConverter<XPrintMainSystemStatus> {
        public override XPrintMainSystemStatus Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseXPrintMainSystemStatus();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, XPrintMainSystemStatus value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
