// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(XPrintPrintHeadTemperatureStatusJsonConverter))]
    public enum XPrintPrintHeadTemperatureStatus {
        NoErrors,
        PrintHeadWarming,
        PrintHeadUnderTemperature,
        PrintHeadOverTemperature,
        PrintHeadTemperatureNotAvailable,
        HeaterTemperatureNotAvailable,
        HeaterAndCoolingFanDriverFault,
    }

    internal static class XPrintPrintHeadTemperatureStatusExtensions {
        public static string ToWireValue(this XPrintPrintHeadTemperatureStatus value) {
            return value switch
            {
                XPrintPrintHeadTemperatureStatus.NoErrors => "NoErrors",
                XPrintPrintHeadTemperatureStatus.PrintHeadWarming => "PrintHeadWarming",
                XPrintPrintHeadTemperatureStatus.PrintHeadUnderTemperature => "PrintHeadUnderTemperature",
                XPrintPrintHeadTemperatureStatus.PrintHeadOverTemperature => "PrintHeadOverTemperature",
                XPrintPrintHeadTemperatureStatus.PrintHeadTemperatureNotAvailable => "PrintHeadTemperatureNotAvailable",
                XPrintPrintHeadTemperatureStatus.HeaterTemperatureNotAvailable => "HeaterTemperatureNotAvailable",
                XPrintPrintHeadTemperatureStatus.HeaterAndCoolingFanDriverFault => "HeaterAndCoolingFanDriverFault",
                _ => value.ToString(),
            };
        }

        public static XPrintPrintHeadTemperatureStatus ParseXPrintPrintHeadTemperatureStatus(this string value) {
            return value switch
            {
                "NoErrors" => XPrintPrintHeadTemperatureStatus.NoErrors,
                "PrintHeadWarming" => XPrintPrintHeadTemperatureStatus.PrintHeadWarming,
                "PrintHeadUnderTemperature" => XPrintPrintHeadTemperatureStatus.PrintHeadUnderTemperature,
                "PrintHeadOverTemperature" => XPrintPrintHeadTemperatureStatus.PrintHeadOverTemperature,
                "PrintHeadTemperatureNotAvailable" => XPrintPrintHeadTemperatureStatus.PrintHeadTemperatureNotAvailable,
                "HeaterTemperatureNotAvailable" => XPrintPrintHeadTemperatureStatus.HeaterTemperatureNotAvailable,
                "HeaterAndCoolingFanDriverFault" => XPrintPrintHeadTemperatureStatus.HeaterAndCoolingFanDriverFault,
                _ => throw new System.ArgumentException($"Unknown XPrintPrintHeadTemperatureStatus value: {value}"),
            };
        }
    }

    internal sealed class XPrintPrintHeadTemperatureStatusJsonConverter : System.Text.Json.Serialization.JsonConverter<XPrintPrintHeadTemperatureStatus> {
        public override XPrintPrintHeadTemperatureStatus Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseXPrintPrintHeadTemperatureStatus();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, XPrintPrintHeadTemperatureStatus value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
