// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(XPrintCappingInfoJsonConverter))]
    public enum XPrintCappingInfo {
        WiperUp,
        CappingUp,
        CappingPumpOn,
        CappingShieldUp,
    }

    internal static class XPrintCappingInfoExtensions {
        public static string ToWireValue(this XPrintCappingInfo value) {
            return value switch
            {
                XPrintCappingInfo.WiperUp => "WiperUp",
                XPrintCappingInfo.CappingUp => "CappingUp",
                XPrintCappingInfo.CappingPumpOn => "CappingPumpOn",
                XPrintCappingInfo.CappingShieldUp => "CappingShieldUp",
                _ => value.ToString(),
            };
        }

        public static XPrintCappingInfo ParseXPrintCappingInfo(this string value) {
            return value switch
            {
                "WiperUp" => XPrintCappingInfo.WiperUp,
                "CappingUp" => XPrintCappingInfo.CappingUp,
                "CappingPumpOn" => XPrintCappingInfo.CappingPumpOn,
                "CappingShieldUp" => XPrintCappingInfo.CappingShieldUp,
                _ => throw new System.ArgumentException($"Unknown XPrintCappingInfo value: {value}"),
            };
        }
    }

    internal sealed class XPrintCappingInfoJsonConverter : System.Text.Json.Serialization.JsonConverter<XPrintCappingInfo> {
        public override XPrintCappingInfo Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseXPrintCappingInfo();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, XPrintCappingInfo value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
