// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace Aida.Api.Client {
    [JsonConverter(typeof(XPrintHeadAxisPositionFlagsJsonConverter))]
    public enum XPrintHeadAxisPositionFlags {
        Capping,
        Print,
        Wiper,
        Calibration,
    }

    internal static class XPrintHeadAxisPositionFlagsExtensions {
        public static string ToWireValue(this XPrintHeadAxisPositionFlags value) {
            return value switch
            {
                XPrintHeadAxisPositionFlags.Capping => "Capping",
                XPrintHeadAxisPositionFlags.Print => "Print",
                XPrintHeadAxisPositionFlags.Wiper => "Wiper",
                XPrintHeadAxisPositionFlags.Calibration => "Calibration",
                _ => value.ToString(),
            };
        }

        public static XPrintHeadAxisPositionFlags ParseXPrintHeadAxisPositionFlags(this string value) {
            return value switch
            {
                "Capping" => XPrintHeadAxisPositionFlags.Capping,
                "Print" => XPrintHeadAxisPositionFlags.Print,
                "Wiper" => XPrintHeadAxisPositionFlags.Wiper,
                "Calibration" => XPrintHeadAxisPositionFlags.Calibration,
                _ => throw new System.ArgumentException($"Unknown XPrintHeadAxisPositionFlags value: {value}"),
            };
        }
    }

    internal sealed class XPrintHeadAxisPositionFlagsJsonConverter : System.Text.Json.Serialization.JsonConverter<XPrintHeadAxisPositionFlags> {
        public override XPrintHeadAxisPositionFlags Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
            var s = reader.GetString() ?? string.Empty;
            return s.ParseXPrintHeadAxisPositionFlags();
        }
        public override void Write(System.Text.Json.Utf8JsonWriter writer, XPrintHeadAxisPositionFlags value, System.Text.Json.JsonSerializerOptions options) {
            writer.WriteStringValue(value.ToWireValue());
        }
    }
}
