// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Aida.Api.Client {
    public partial class ConfigurationApi {
        private readonly HttpClient _http;
        private readonly Uri _baseUrl;
        /// <summary>Discriminated per-status result surface; never throws for modeled statuses.</summary>
        public ResultsClient Results { get; }
        /// <summary>Raw HTTP surface; returns the underlying HttpResponseMessage.</summary>
        public RawClient Raw { get; }

        public ConfigurationApi(HttpClient http, Uri baseUrl) {
            _http = http ?? throw new ArgumentNullException(nameof(http));
            _baseUrl = baseUrl ?? throw new ArgumentNullException(nameof(baseUrl));
            Results = new ResultsClient(this);
            Raw = new RawClient(this);
        }

        private async Task<HttpResponseMessage> SendGetConfigurationKeysAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/configuration/keys";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<global::System.Collections.Generic.IDictionary<string, string>> GetConfigurationKeysAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetConfigurationKeysAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<global::System.Collections.Generic.IDictionary<string, string>>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetConfigurationKeys {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGetPrinterNameAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/configuration/printer-name";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<string> GetPrinterNameAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetPrinterNameAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<string>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetPrinterName {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendReloadConfigurationAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/configuration/reload";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task ReloadConfigurationAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendReloadConfigurationAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"ReloadConfiguration {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendUpdateConfigFileAsync(string? scannerId = default, global::System.Collections.Generic.IList<FormFile>? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/configuration/upload";
            var __query = new StringBuilder();
            if (scannerId is not null)
            {
                __query.Append("?scannerId=").Append(Uri.EscapeDataString(scannerId ?? string.Empty));
            }
            var __url = new Uri(_baseUrl, __relPath + __query.ToString());
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task UpdateConfigFileAsync(string? scannerId = default, global::System.Collections.Generic.IList<FormFile>? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendUpdateConfigFileAsync(scannerId, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"UpdateConfigFile {__status} {__resp.ReasonPhrase}");
        }

        /// <summary>Typed per-status result surface. Result types live in the &lt;c&gt;.Responses&lt;/c&gt; sub-namespace so they never collide with DTO names from the spec.</summary>
        public sealed class ResultsClient {
            private readonly ConfigurationApi _outer;

            internal ResultsClient(ConfigurationApi outer) { _outer = outer; }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetConfigurationKeysResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetConfigurationKeysResult> GetConfigurationKeysAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetConfigurationKeysAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        global::System.Collections.Generic.IDictionary<string, string>? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<global::System.Collections.Generic.IDictionary<string, string>>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetConfigurationKeysResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetConfigurationKeysResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetPrinterNameResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetPrinterNameResult> GetPrinterNameAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetPrinterNameAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        string? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<string>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetPrinterNameResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetPrinterNameResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.ReloadConfigurationResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.ReloadConfigurationResult> ReloadConfigurationAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendReloadConfigurationAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.ReloadConfigurationResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.ReloadConfigurationResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.UpdateConfigFileResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.UpdateConfigFileResult> UpdateConfigFileAsync(string? scannerId = default, global::System.Collections.Generic.IList<FormFile>? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendUpdateConfigFileAsync(scannerId, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.UpdateConfigFileResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.UpdateConfigFileResult.FromOther(__status, __rawBody);
                    }
                }
            }
        }

        /// <summary>Returns the underlying HttpResponseMessage unchanged. Caller must dispose.</summary>
        public sealed class RawClient {
            private readonly ConfigurationApi _outer;

            internal RawClient(ConfigurationApi outer) { _outer = outer; }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetConfigurationKeysAsync(CancellationToken cancellationToken = default)
                => _outer.SendGetConfigurationKeysAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetPrinterNameAsync(CancellationToken cancellationToken = default)
                => _outer.SendGetPrinterNameAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> ReloadConfigurationAsync(CancellationToken cancellationToken = default)
                => _outer.SendReloadConfigurationAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> UpdateConfigFileAsync(string? scannerId = default, global::System.Collections.Generic.IList<FormFile>? body = default, CancellationToken cancellationToken = default)
                => _outer.SendUpdateConfigFileAsync(scannerId, body, cancellationToken);
        }
    }
}
