// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Aida.Api.Client {
    public partial class DisplayDataApi {
        private readonly HttpClient _http;
        private readonly Uri _baseUrl;
        /// <summary>Discriminated per-status result surface; never throws for modeled statuses.</summary>
        public ResultsClient Results { get; }
        /// <summary>Raw HTTP surface; returns the underlying HttpResponseMessage.</summary>
        public RawClient Raw { get; }

        public DisplayDataApi(HttpClient http, Uri baseUrl) {
            _http = http ?? throw new ArgumentNullException(nameof(http));
            _baseUrl = baseUrl ?? throw new ArgumentNullException(nameof(baseUrl));
            Results = new ResultsClient(this);
            Raw = new RawClient(this);
        }

        private async Task<HttpResponseMessage> SendVerifyPinAsync(string? enteredPin = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/display-data/api-keys";
            var __query = new StringBuilder();
            if (enteredPin is not null)
            {
                __query.Append("?enteredPin=").Append(Uri.EscapeDataString(enteredPin ?? string.Empty));
            }
            var __url = new Uri(_baseUrl, __relPath + __query.ToString());
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<bool> VerifyPinAsync(string? enteredPin = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendVerifyPinAsync(enteredPin, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<bool>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"VerifyPin {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendIssuanceStatusAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/display-data/issuancestatus";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<DisplayIssuanceStatusDto> IssuanceStatusAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendIssuanceStatusAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<DisplayIssuanceStatusDto>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"IssuanceStatus {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendLaserStatusAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/display-data/laserstatus";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<DisplayLaserStatusDto> LaserStatusAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendLaserStatusAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<DisplayLaserStatusDto>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"LaserStatus {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendSystemStatusAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/display-data/systemstatus";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<DisplaySystemStatusDto> SystemStatusAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendSystemStatusAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<DisplaySystemStatusDto>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"SystemStatus {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendTransportStatusAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/display-data/transportstatus";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<DisplayTransportStatusDto> TransportStatusAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendTransportStatusAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<DisplayTransportStatusDto>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"TransportStatus {__status} {__resp.ReasonPhrase}");
        }

        /// <summary>Typed per-status result surface. Result types live in the &lt;c&gt;.Responses&lt;/c&gt; sub-namespace so they never collide with DTO names from the spec.</summary>
        public sealed class ResultsClient {
            private readonly DisplayDataApi _outer;

            internal ResultsClient(DisplayDataApi outer) { _outer = outer; }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.VerifyPinResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.VerifyPinResult> VerifyPinAsync(string? enteredPin = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendVerifyPinAsync(enteredPin, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        bool? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<bool>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.VerifyPinResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.VerifyPinResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.IssuanceStatusResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.IssuanceStatusResult> IssuanceStatusAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendIssuanceStatusAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        DisplayIssuanceStatusDto? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<DisplayIssuanceStatusDto>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.IssuanceStatusResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.IssuanceStatusResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.LaserStatusResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.LaserStatusResult> LaserStatusAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendLaserStatusAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        DisplayLaserStatusDto? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<DisplayLaserStatusDto>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.LaserStatusResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.LaserStatusResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.SystemStatusResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.SystemStatusResult> SystemStatusAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendSystemStatusAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        DisplaySystemStatusDto? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<DisplaySystemStatusDto>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.SystemStatusResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.SystemStatusResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.TransportStatusResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.TransportStatusResult> TransportStatusAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendTransportStatusAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        DisplayTransportStatusDto? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<DisplayTransportStatusDto>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.TransportStatusResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.TransportStatusResult.FromOther(__status, __rawBody);
                    }
                }
            }
        }

        /// <summary>Returns the underlying HttpResponseMessage unchanged. Caller must dispose.</summary>
        public sealed class RawClient {
            private readonly DisplayDataApi _outer;

            internal RawClient(DisplayDataApi outer) { _outer = outer; }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> VerifyPinAsync(string? enteredPin = default, CancellationToken cancellationToken = default)
                => _outer.SendVerifyPinAsync(enteredPin, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> IssuanceStatusAsync(CancellationToken cancellationToken = default)
                => _outer.SendIssuanceStatusAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> LaserStatusAsync(CancellationToken cancellationToken = default)
                => _outer.SendLaserStatusAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> SystemStatusAsync(CancellationToken cancellationToken = default)
                => _outer.SendSystemStatusAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> TransportStatusAsync(CancellationToken cancellationToken = default)
                => _outer.SendTransportStatusAsync(cancellationToken);
        }
    }
}
