// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Aida.Api.Client {
    public partial class EtlApi {
        private readonly HttpClient _http;
        private readonly Uri _baseUrl;
        /// <summary>Discriminated per-status result surface; never throws for modeled statuses.</summary>
        public ResultsClient Results { get; }
        /// <summary>Raw HTTP surface; returns the underlying HttpResponseMessage.</summary>
        public RawClient Raw { get; }

        public EtlApi(HttpClient http, Uri baseUrl) {
            _http = http ?? throw new ArgumentNullException(nameof(http));
            _baseUrl = baseUrl ?? throw new ArgumentNullException(nameof(baseUrl));
            Results = new ResultsClient(this);
            Raw = new RawClient(this);
        }

        private async Task<HttpResponseMessage> SendCreateDataExchangeTableAsync(int jobId, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/etl/{Uri.EscapeDataString(jobId.ToString(System.Globalization.CultureInfo.InvariantCulture))}/create-data-exchange-table";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<DataSourceConfigurationDto> CreateDataExchangeTableAsync(int jobId, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendCreateDataExchangeTableAsync(jobId, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<DataSourceConfigurationDto>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"CreateDataExchangeTable {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGetDataBindingsAsync(int jobId, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/etl/{Uri.EscapeDataString(jobId.ToString(System.Globalization.CultureInfo.InvariantCulture))}/data-bindings";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<global::System.Collections.Generic.IDictionary<string, global::System.Collections.Generic.IList<DataBindingDto>>> GetDataBindingsAsync(int jobId, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetDataBindingsAsync(jobId, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<global::System.Collections.Generic.IDictionary<string, global::System.Collections.Generic.IList<DataBindingDto>>>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetDataBindings {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendDataSourceConfigurationIsValidAsync(int jobId, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/etl/{Uri.EscapeDataString(jobId.ToString(System.Globalization.CultureInfo.InvariantCulture))}/data-source/is-valid";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<bool> DataSourceConfigurationIsValidAsync(int jobId, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendDataSourceConfigurationIsValidAsync(jobId, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<bool>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"DataSourceConfigurationIsValid {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGetEntityDescriptorsByJobTemplateIdAsync(int jobId, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/etl/{Uri.EscapeDataString(jobId.ToString(System.Globalization.CultureInfo.InvariantCulture))}/entities";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<global::System.Collections.Generic.IList<EntityDescriptor>> GetEntityDescriptorsByJobTemplateIdAsync(int jobId, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetEntityDescriptorsByJobTemplateIdAsync(jobId, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<global::System.Collections.Generic.IList<EntityDescriptor>>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetEntityDescriptorsByJobTemplateId {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGetDataExchangeTableDefinitionAsync(int jobId, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/etl/{Uri.EscapeDataString(jobId.ToString(System.Globalization.CultureInfo.InvariantCulture))}/exchange-table-ddl";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<DataExchangeTableDefinition> GetDataExchangeTableDefinitionAsync(int jobId, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetDataExchangeTableDefinitionAsync(jobId, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<DataExchangeTableDefinition>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetDataExchangeTableDefinition {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGenerateDataSourceAsync(int jobId, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/etl/{Uri.EscapeDataString(jobId.ToString(System.Globalization.CultureInfo.InvariantCulture))}/generate-datasource";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<DataSourceConfigurationDto> GenerateDataSourceAsync(int jobId, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGenerateDataSourceAsync(jobId, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<DataSourceConfigurationDto>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GenerateDataSource {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGenerateMockDatasetAsync(int jobId, global::System.Collections.Generic.IList<DataRecord>? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/etl/{Uri.EscapeDataString(jobId.ToString(System.Globalization.CultureInfo.InvariantCulture))}/generate-mock-dataset";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task GenerateMockDatasetAsync(int jobId, global::System.Collections.Generic.IList<DataRecord>? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGenerateMockDatasetAsync(jobId, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GenerateMockDataset {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGetTableDdlAsync(int jobId, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/etl/{Uri.EscapeDataString(jobId.ToString(System.Globalization.CultureInfo.InvariantCulture))}/get-data-exchange-table-ddl";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<string> GetTableDdlAsync(int jobId, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetTableDdlAsync(jobId, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<string>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetTableDdl {__status} {__resp.ReasonPhrase}");
        }

        /// <summary>Typed per-status result surface. Result types live in the &lt;c&gt;.Responses&lt;/c&gt; sub-namespace so they never collide with DTO names from the spec.</summary>
        public sealed class ResultsClient {
            private readonly EtlApi _outer;

            internal ResultsClient(EtlApi outer) { _outer = outer; }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.CreateDataExchangeTableResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.CreateDataExchangeTableResult> CreateDataExchangeTableAsync(int jobId, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendCreateDataExchangeTableAsync(jobId, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        DataSourceConfigurationDto? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<DataSourceConfigurationDto>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.CreateDataExchangeTableResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.CreateDataExchangeTableResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetDataBindingsResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetDataBindingsResult> GetDataBindingsAsync(int jobId, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetDataBindingsAsync(jobId, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        global::System.Collections.Generic.IDictionary<string, global::System.Collections.Generic.IList<DataBindingDto>>? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<global::System.Collections.Generic.IDictionary<string, global::System.Collections.Generic.IList<DataBindingDto>>>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetDataBindingsResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetDataBindingsResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.DataSourceConfigurationIsValidResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.DataSourceConfigurationIsValidResult> DataSourceConfigurationIsValidAsync(int jobId, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendDataSourceConfigurationIsValidAsync(jobId, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        bool? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<bool>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.DataSourceConfigurationIsValidResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.DataSourceConfigurationIsValidResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetEntityDescriptorsByJobTemplateIdResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetEntityDescriptorsByJobTemplateIdResult> GetEntityDescriptorsByJobTemplateIdAsync(int jobId, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetEntityDescriptorsByJobTemplateIdAsync(jobId, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        global::System.Collections.Generic.IList<EntityDescriptor>? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<global::System.Collections.Generic.IList<EntityDescriptor>>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetEntityDescriptorsByJobTemplateIdResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetEntityDescriptorsByJobTemplateIdResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetDataExchangeTableDefinitionResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetDataExchangeTableDefinitionResult> GetDataExchangeTableDefinitionAsync(int jobId, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetDataExchangeTableDefinitionAsync(jobId, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        DataExchangeTableDefinition? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<DataExchangeTableDefinition>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetDataExchangeTableDefinitionResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetDataExchangeTableDefinitionResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GenerateDataSourceResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GenerateDataSourceResult> GenerateDataSourceAsync(int jobId, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGenerateDataSourceAsync(jobId, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        DataSourceConfigurationDto? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<DataSourceConfigurationDto>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GenerateDataSourceResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GenerateDataSourceResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GenerateMockDatasetResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GenerateMockDatasetResult> GenerateMockDatasetAsync(int jobId, global::System.Collections.Generic.IList<DataRecord>? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGenerateMockDatasetAsync(jobId, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.GenerateMockDatasetResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GenerateMockDatasetResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetTableDdlResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetTableDdlResult> GetTableDdlAsync(int jobId, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetTableDdlAsync(jobId, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        string? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<string>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetTableDdlResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetTableDdlResult.FromOther(__status, __rawBody);
                    }
                }
            }
        }

        /// <summary>Returns the underlying HttpResponseMessage unchanged. Caller must dispose.</summary>
        public sealed class RawClient {
            private readonly EtlApi _outer;

            internal RawClient(EtlApi outer) { _outer = outer; }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> CreateDataExchangeTableAsync(int jobId, CancellationToken cancellationToken = default)
                => _outer.SendCreateDataExchangeTableAsync(jobId, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetDataBindingsAsync(int jobId, CancellationToken cancellationToken = default)
                => _outer.SendGetDataBindingsAsync(jobId, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> DataSourceConfigurationIsValidAsync(int jobId, CancellationToken cancellationToken = default)
                => _outer.SendDataSourceConfigurationIsValidAsync(jobId, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetEntityDescriptorsByJobTemplateIdAsync(int jobId, CancellationToken cancellationToken = default)
                => _outer.SendGetEntityDescriptorsByJobTemplateIdAsync(jobId, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetDataExchangeTableDefinitionAsync(int jobId, CancellationToken cancellationToken = default)
                => _outer.SendGetDataExchangeTableDefinitionAsync(jobId, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GenerateDataSourceAsync(int jobId, CancellationToken cancellationToken = default)
                => _outer.SendGenerateDataSourceAsync(jobId, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GenerateMockDatasetAsync(int jobId, global::System.Collections.Generic.IList<DataRecord>? body = default, CancellationToken cancellationToken = default)
                => _outer.SendGenerateMockDatasetAsync(jobId, body, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetTableDdlAsync(int jobId, CancellationToken cancellationToken = default)
                => _outer.SendGetTableDdlAsync(jobId, cancellationToken);
        }
    }
}
