// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Aida.Api.Client {
    public partial class MachineApi {
        private readonly HttpClient _http;
        private readonly Uri _baseUrl;
        /// <summary>Discriminated per-status result surface; never throws for modeled statuses.</summary>
        public ResultsClient Results { get; }
        /// <summary>Raw HTTP surface; returns the underlying HttpResponseMessage.</summary>
        public RawClient Raw { get; }

        public MachineApi(HttpClient http, Uri baseUrl) {
            _http = http ?? throw new ArgumentNullException(nameof(http));
            _baseUrl = baseUrl ?? throw new ArgumentNullException(nameof(baseUrl));
            Results = new ResultsClient(this);
            Raw = new RawClient(this);
        }

        private async Task<HttpResponseMessage> SendGetDeviceDescriptorByIdAsync(string id, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/machine/device/{Uri.EscapeDataString(id)}";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<DeviceDefinition> GetDeviceDescriptorByIdAsync(string id, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetDeviceDescriptorByIdAsync(id, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<DeviceDefinition>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetDeviceDescriptorById {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGetSystemInformationAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/machine/info";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task GetSystemInformationAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetSystemInformationAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetSystemInformation {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendListModulesAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/machine/modules";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<global::System.Collections.Generic.IList<ModuleDefinition>> ListModulesAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendListModulesAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<global::System.Collections.Generic.IList<ModuleDefinition>>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"ListModules {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendListDevicesByModuleAsync(string moduleId, global::System.Collections.Generic.IList<DeviceType>? deviceType = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/machine/modules/{Uri.EscapeDataString(moduleId)}/devices";
            var __query = new StringBuilder();
            if (deviceType is not null)
            {
                __query.Append("?deviceType=").Append(Uri.EscapeDataString(string.Join(",", deviceType)));
            }
            var __url = new Uri(_baseUrl, __relPath + __query.ToString());
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<global::System.Collections.Generic.IList<DeviceDefinition>> ListDevicesByModuleAsync(string moduleId, global::System.Collections.Generic.IList<DeviceType>? deviceType = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendListDevicesByModuleAsync(moduleId, deviceType, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<global::System.Collections.Generic.IList<DeviceDefinition>>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"ListDevicesByModule {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGetMachineAddressesAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/machine/network/addresses";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<global::System.Collections.Generic.IList<string>> GetMachineAddressesAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetMachineAddressesAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<global::System.Collections.Generic.IList<string>>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetMachineAddresses {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendListScannersAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/machine/scanners";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<global::System.Collections.Generic.IList<ScannerModuleDefinition>> ListScannersAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendListScannersAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<global::System.Collections.Generic.IList<ScannerModuleDefinition>>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"ListScanners {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGetMachineStatusAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/machine/status";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<MachineStatusDto> GetMachineStatusAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetMachineStatusAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<MachineStatusDto>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetMachineStatus {__status} {__resp.ReasonPhrase}");
        }

        /// <summary>Typed per-status result surface. Result types live in the &lt;c&gt;.Responses&lt;/c&gt; sub-namespace so they never collide with DTO names from the spec.</summary>
        public sealed class ResultsClient {
            private readonly MachineApi _outer;

            internal ResultsClient(MachineApi outer) { _outer = outer; }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetDeviceDescriptorByIdResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetDeviceDescriptorByIdResult> GetDeviceDescriptorByIdAsync(string id, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetDeviceDescriptorByIdAsync(id, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        DeviceDefinition? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<DeviceDefinition>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetDeviceDescriptorByIdResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetDeviceDescriptorByIdResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetSystemInformationResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetSystemInformationResult> GetSystemInformationAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetSystemInformationAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.GetSystemInformationResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetSystemInformationResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.ListModulesResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.ListModulesResult> ListModulesAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendListModulesAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        global::System.Collections.Generic.IList<ModuleDefinition>? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<global::System.Collections.Generic.IList<ModuleDefinition>>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.ListModulesResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.ListModulesResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.ListDevicesByModuleResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.ListDevicesByModuleResult> ListDevicesByModuleAsync(string moduleId, global::System.Collections.Generic.IList<DeviceType>? deviceType = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendListDevicesByModuleAsync(moduleId, deviceType, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        global::System.Collections.Generic.IList<DeviceDefinition>? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<global::System.Collections.Generic.IList<DeviceDefinition>>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.ListDevicesByModuleResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.ListDevicesByModuleResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetMachineAddressesResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetMachineAddressesResult> GetMachineAddressesAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetMachineAddressesAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        global::System.Collections.Generic.IList<string>? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<global::System.Collections.Generic.IList<string>>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetMachineAddressesResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetMachineAddressesResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.ListScannersResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.ListScannersResult> ListScannersAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendListScannersAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        global::System.Collections.Generic.IList<ScannerModuleDefinition>? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<global::System.Collections.Generic.IList<ScannerModuleDefinition>>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.ListScannersResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.ListScannersResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetMachineStatusResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetMachineStatusResult> GetMachineStatusAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetMachineStatusAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        MachineStatusDto? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<MachineStatusDto>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetMachineStatusResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetMachineStatusResult.FromOther(__status, __rawBody);
                    }
                }
            }
        }

        /// <summary>Returns the underlying HttpResponseMessage unchanged. Caller must dispose.</summary>
        public sealed class RawClient {
            private readonly MachineApi _outer;

            internal RawClient(MachineApi outer) { _outer = outer; }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetDeviceDescriptorByIdAsync(string id, CancellationToken cancellationToken = default)
                => _outer.SendGetDeviceDescriptorByIdAsync(id, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetSystemInformationAsync(CancellationToken cancellationToken = default)
                => _outer.SendGetSystemInformationAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> ListModulesAsync(CancellationToken cancellationToken = default)
                => _outer.SendListModulesAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> ListDevicesByModuleAsync(string moduleId, global::System.Collections.Generic.IList<DeviceType>? deviceType = default, CancellationToken cancellationToken = default)
                => _outer.SendListDevicesByModuleAsync(moduleId, deviceType, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetMachineAddressesAsync(CancellationToken cancellationToken = default)
                => _outer.SendGetMachineAddressesAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> ListScannersAsync(CancellationToken cancellationToken = default)
                => _outer.SendListScannersAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetMachineStatusAsync(CancellationToken cancellationToken = default)
                => _outer.SendGetMachineStatusAsync(cancellationToken);
        }
    }
}
