// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Aida.Api.Client {
    public partial class MagneticEncoderApi {
        private readonly HttpClient _http;
        private readonly Uri _baseUrl;
        /// <summary>Discriminated per-status result surface; never throws for modeled statuses.</summary>
        public ResultsClient Results { get; }
        /// <summary>Raw HTTP surface; returns the underlying HttpResponseMessage.</summary>
        public RawClient Raw { get; }

        public MagneticEncoderApi(HttpClient http, Uri baseUrl) {
            _http = http ?? throw new ArgumentNullException(nameof(http));
            _baseUrl = baseUrl ?? throw new ArgumentNullException(nameof(baseUrl));
            Results = new ResultsClient(this);
            Raw = new RawClient(this);
        }

        private async Task<HttpResponseMessage> SendReadDataAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/magneticencoder/read";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<MagStripeDataDto> ReadDataAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendReadDataAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<MagStripeDataDto>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"ReadData {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendWriteDataAsync(bool? useHiCoercivity = default, MagStripeDataDto? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/magneticencoder/write";
            var __query = new StringBuilder();
            if (useHiCoercivity.HasValue)
            {
                __query.Append("?useHiCoercivity=").Append(Uri.EscapeDataString(useHiCoercivity.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty));
            }
            var __url = new Uri(_baseUrl, __relPath + __query.ToString());
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task WriteDataAsync(bool? useHiCoercivity = default, MagStripeDataDto? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendWriteDataAsync(useHiCoercivity, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"WriteData {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGetMagneticConfigurationAsync(int jobTemplateId, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/magneticencoder/{Uri.EscapeDataString(jobTemplateId.ToString(System.Globalization.CultureInfo.InvariantCulture))}/configuration";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<MagneticStripeConfigurationDto> GetMagneticConfigurationAsync(int jobTemplateId, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetMagneticConfigurationAsync(jobTemplateId, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<MagneticStripeConfigurationDto>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetMagneticConfiguration {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendUpdateMagneticConfigurationAsync(int jobTemplateId, MagneticStripeConfigurationDto? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/magneticencoder/{Uri.EscapeDataString(jobTemplateId.ToString(System.Globalization.CultureInfo.InvariantCulture))}/configuration";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task UpdateMagneticConfigurationAsync(int jobTemplateId, MagneticStripeConfigurationDto? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendUpdateMagneticConfigurationAsync(jobTemplateId, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"UpdateMagneticConfiguration {__status} {__resp.ReasonPhrase}");
        }

        /// <summary>Typed per-status result surface. Result types live in the &lt;c&gt;.Responses&lt;/c&gt; sub-namespace so they never collide with DTO names from the spec.</summary>
        public sealed class ResultsClient {
            private readonly MagneticEncoderApi _outer;

            internal ResultsClient(MagneticEncoderApi outer) { _outer = outer; }

            public async Task<global::Aida.Api.Client.Responses.ReadDataResult> ReadDataAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendReadDataAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        MagStripeDataDto? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<MagStripeDataDto>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.ReadDataResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.ReadDataResult.FromOther(__status, __rawBody);
                    }
                }
            }

            public async Task<global::Aida.Api.Client.Responses.WriteDataResult> WriteDataAsync(bool? useHiCoercivity = default, MagStripeDataDto? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendWriteDataAsync(useHiCoercivity, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.WriteDataResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.WriteDataResult.FromOther(__status, __rawBody);
                    }
                }
            }

            public async Task<global::Aida.Api.Client.Responses.GetMagneticConfigurationResult> GetMagneticConfigurationAsync(int jobTemplateId, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetMagneticConfigurationAsync(jobTemplateId, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        MagneticStripeConfigurationDto? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<MagneticStripeConfigurationDto>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetMagneticConfigurationResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetMagneticConfigurationResult.FromOther(__status, __rawBody);
                    }
                }
            }

            public async Task<global::Aida.Api.Client.Responses.UpdateMagneticConfigurationResult> UpdateMagneticConfigurationAsync(int jobTemplateId, MagneticStripeConfigurationDto? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendUpdateMagneticConfigurationAsync(jobTemplateId, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.UpdateMagneticConfigurationResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.UpdateMagneticConfigurationResult.FromOther(__status, __rawBody);
                    }
                }
            }
        }

        /// <summary>Returns the underlying HttpResponseMessage unchanged. Caller must dispose.</summary>
        public sealed class RawClient {
            private readonly MagneticEncoderApi _outer;

            internal RawClient(MagneticEncoderApi outer) { _outer = outer; }

            public Task<HttpResponseMessage> ReadDataAsync(CancellationToken cancellationToken = default)
                => _outer.SendReadDataAsync(cancellationToken);

            public Task<HttpResponseMessage> WriteDataAsync(bool? useHiCoercivity = default, MagStripeDataDto? body = default, CancellationToken cancellationToken = default)
                => _outer.SendWriteDataAsync(useHiCoercivity, body, cancellationToken);

            public Task<HttpResponseMessage> GetMagneticConfigurationAsync(int jobTemplateId, CancellationToken cancellationToken = default)
                => _outer.SendGetMagneticConfigurationAsync(jobTemplateId, cancellationToken);

            public Task<HttpResponseMessage> UpdateMagneticConfigurationAsync(int jobTemplateId, MagneticStripeConfigurationDto? body = default, CancellationToken cancellationToken = default)
                => _outer.SendUpdateMagneticConfigurationAsync(jobTemplateId, body, cancellationToken);
        }
    }
}
