// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Aida.Api.Client {
    public partial class ModbusApi {
        private readonly HttpClient _http;
        private readonly Uri _baseUrl;
        /// <summary>Discriminated per-status result surface; never throws for modeled statuses.</summary>
        public ResultsClient Results { get; }
        /// <summary>Raw HTTP surface; returns the underlying HttpResponseMessage.</summary>
        public RawClient Raw { get; }

        public ModbusApi(HttpClient http, Uri baseUrl) {
            _http = http ?? throw new ArgumentNullException(nameof(http));
            _baseUrl = baseUrl ?? throw new ArgumentNullException(nameof(baseUrl));
            Results = new ResultsClient(this);
            Raw = new RawClient(this);
        }

        private async Task<HttpResponseMessage> SendGetModbusClientsAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/clients";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task GetModbusClientsAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetModbusClientsAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetModbusClients {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendExportRegistersAsync(string? com = default, int? slaveId = default, global::System.Collections.Generic.IList<int>? includedRegisters = default, int? startRegister = default, int? endRegister = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/export-registers";
            var __query = new StringBuilder();
            if (com is not null)
            {
                __query.Append("?com=").Append(Uri.EscapeDataString(com ?? string.Empty));
            }
            if (slaveId.HasValue)
            {
                __query.Append("&slaveId=").Append(Uri.EscapeDataString(slaveId.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty));
            }
            if (includedRegisters is not null)
            {
                __query.Append("&includedRegisters=").Append(Uri.EscapeDataString(string.Join(",", includedRegisters)));
            }
            if (startRegister.HasValue)
            {
                __query.Append("&startRegister=").Append(Uri.EscapeDataString(startRegister.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty));
            }
            if (endRegister.HasValue)
            {
                __query.Append("&endRegister=").Append(Uri.EscapeDataString(endRegister.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty));
            }
            var __url = new Uri(_baseUrl, __relPath + __query.ToString());
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<DeviceRegistersValues> ExportRegistersAsync(string? com = default, int? slaveId = default, global::System.Collections.Generic.IList<int>? includedRegisters = default, int? startRegister = default, int? endRegister = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendExportRegistersAsync(com, slaveId, includedRegisters, startRegister, endRegister, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<DeviceRegistersValues>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"ExportRegisters {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendImportRegistersAsync(ImportRegistersRequest? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/import-registers";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task ImportRegistersAsync(ImportRegistersRequest? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendImportRegistersAsync(body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"ImportRegisters {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendReadFloat32RegistersAsync(string port, ReadFieldRequest? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/{Uri.EscapeDataString(port)}/read-float32";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<float> ReadFloat32RegistersAsync(string port, ReadFieldRequest? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendReadFloat32RegistersAsync(port, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<float>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"ReadFloat32Registers {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendReadHoldingRegistersAsync(string port, ReadHoldingRegistersRequest? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/{Uri.EscapeDataString(port)}/read-holding-registers";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task ReadHoldingRegistersAsync(string port, ReadHoldingRegistersRequest? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendReadHoldingRegistersAsync(port, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"ReadHoldingRegisters {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendReadInt16Async(string port, ReadFieldRequest? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/{Uri.EscapeDataString(port)}/read-int16";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<int> ReadInt16Async(string port, ReadFieldRequest? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendReadInt16Async(port, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<int>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"ReadInt16 {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendReadInt32Async(string port, ReadFieldRequest? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/{Uri.EscapeDataString(port)}/read-int32";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<int> ReadInt32Async(string port, ReadFieldRequest? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendReadInt32Async(port, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<int>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"ReadInt32 {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendWriteFloat32Async(string port, WriteFloat32Request? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/{Uri.EscapeDataString(port)}/write-float32";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task WriteFloat32Async(string port, WriteFloat32Request? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendWriteFloat32Async(port, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"WriteFloat32 {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendWriteInt16Async(string port, WriteInt16Request? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/{Uri.EscapeDataString(port)}/write-int16";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task WriteInt16Async(string port, WriteInt16Request? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendWriteInt16Async(port, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"WriteInt16 {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendWriteInt32Async(string port, WriteInt32Request? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/{Uri.EscapeDataString(port)}/write-int32";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task WriteInt32Async(string port, WriteInt32Request? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendWriteInt32Async(port, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"WriteInt32 {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendWriteStringAsync(string port, WriteMultipleRegistersRequest? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/{Uri.EscapeDataString(port)}/write-multiple-registers";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task WriteStringAsync(string port, WriteMultipleRegistersRequest? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendWriteStringAsync(port, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"WriteString {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendWriteSingleRegisterAsync(string port, WriteUInt16Request? body = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/{Uri.EscapeDataString(port)}/write-register";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            if (body is not null)
            {
                var __bodyJson = JsonSerializer.Serialize(body, JsonConfig.Options);
                __req.Content = new StringContent(__bodyJson, Encoding.UTF8, "application/json");
            }
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task WriteSingleRegisterAsync(string port, WriteUInt16Request? body = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendWriteSingleRegisterAsync(port, body, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"WriteSingleRegister {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendReadAllRegistersAsync(string slaveIdHex, string port, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/modbus/{Uri.EscapeDataString(port)}/{Uri.EscapeDataString(slaveIdHex)}/registers/all";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<global::System.Collections.Generic.IList<int>> ReadAllRegistersAsync(string slaveIdHex, string port, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendReadAllRegistersAsync(slaveIdHex, port, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<global::System.Collections.Generic.IList<int>>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"ReadAllRegisters {__status} {__resp.ReasonPhrase}");
        }

        /// <summary>Typed per-status result surface. Result types live in the &lt;c&gt;.Responses&lt;/c&gt; sub-namespace so they never collide with DTO names from the spec.</summary>
        public sealed class ResultsClient {
            private readonly ModbusApi _outer;

            internal ResultsClient(ModbusApi outer) { _outer = outer; }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetModbusClientsResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetModbusClientsResult> GetModbusClientsAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetModbusClientsAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.GetModbusClientsResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetModbusClientsResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.ExportRegistersResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.ExportRegistersResult> ExportRegistersAsync(string? com = default, int? slaveId = default, global::System.Collections.Generic.IList<int>? includedRegisters = default, int? startRegister = default, int? endRegister = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendExportRegistersAsync(com, slaveId, includedRegisters, startRegister, endRegister, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        DeviceRegistersValues? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<DeviceRegistersValues>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.ExportRegistersResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.ExportRegistersResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.ImportRegistersResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.ImportRegistersResult> ImportRegistersAsync(ImportRegistersRequest? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendImportRegistersAsync(body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.ImportRegistersResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.ImportRegistersResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.ReadFloat32RegistersResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.ReadFloat32RegistersResult> ReadFloat32RegistersAsync(string port, ReadFieldRequest? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendReadFloat32RegistersAsync(port, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        float? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<float>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.ReadFloat32RegistersResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.ReadFloat32RegistersResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.ReadHoldingRegistersResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.ReadHoldingRegistersResult> ReadHoldingRegistersAsync(string port, ReadHoldingRegistersRequest? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendReadHoldingRegistersAsync(port, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.ReadHoldingRegistersResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.ReadHoldingRegistersResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.ReadInt16Result"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.ReadInt16Result> ReadInt16Async(string port, ReadFieldRequest? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendReadInt16Async(port, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        int? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<int>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.ReadInt16Result.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.ReadInt16Result.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.ReadInt32Result"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.ReadInt32Result> ReadInt32Async(string port, ReadFieldRequest? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendReadInt32Async(port, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        int? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<int>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.ReadInt32Result.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.ReadInt32Result.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.WriteFloat32Result"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.WriteFloat32Result> WriteFloat32Async(string port, WriteFloat32Request? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendWriteFloat32Async(port, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.WriteFloat32Result.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.WriteFloat32Result.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.WriteInt16Result"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.WriteInt16Result> WriteInt16Async(string port, WriteInt16Request? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendWriteInt16Async(port, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.WriteInt16Result.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.WriteInt16Result.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.WriteInt32Result"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.WriteInt32Result> WriteInt32Async(string port, WriteInt32Request? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendWriteInt32Async(port, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.WriteInt32Result.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.WriteInt32Result.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.WriteStringResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.WriteStringResult> WriteStringAsync(string port, WriteMultipleRegistersRequest? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendWriteStringAsync(port, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.WriteStringResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.WriteStringResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.WriteSingleRegisterResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.WriteSingleRegisterResult> WriteSingleRegisterAsync(string port, WriteUInt16Request? body = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendWriteSingleRegisterAsync(port, body, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.WriteSingleRegisterResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.WriteSingleRegisterResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.ReadAllRegistersResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.ReadAllRegistersResult> ReadAllRegistersAsync(string slaveIdHex, string port, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendReadAllRegistersAsync(slaveIdHex, port, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        global::System.Collections.Generic.IList<int>? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<global::System.Collections.Generic.IList<int>>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.ReadAllRegistersResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.ReadAllRegistersResult.FromOther(__status, __rawBody);
                    }
                }
            }
        }

        /// <summary>Returns the underlying HttpResponseMessage unchanged. Caller must dispose.</summary>
        public sealed class RawClient {
            private readonly ModbusApi _outer;

            internal RawClient(ModbusApi outer) { _outer = outer; }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetModbusClientsAsync(CancellationToken cancellationToken = default)
                => _outer.SendGetModbusClientsAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> ExportRegistersAsync(string? com = default, int? slaveId = default, global::System.Collections.Generic.IList<int>? includedRegisters = default, int? startRegister = default, int? endRegister = default, CancellationToken cancellationToken = default)
                => _outer.SendExportRegistersAsync(com, slaveId, includedRegisters, startRegister, endRegister, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> ImportRegistersAsync(ImportRegistersRequest? body = default, CancellationToken cancellationToken = default)
                => _outer.SendImportRegistersAsync(body, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> ReadFloat32RegistersAsync(string port, ReadFieldRequest? body = default, CancellationToken cancellationToken = default)
                => _outer.SendReadFloat32RegistersAsync(port, body, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> ReadHoldingRegistersAsync(string port, ReadHoldingRegistersRequest? body = default, CancellationToken cancellationToken = default)
                => _outer.SendReadHoldingRegistersAsync(port, body, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> ReadInt16Async(string port, ReadFieldRequest? body = default, CancellationToken cancellationToken = default)
                => _outer.SendReadInt16Async(port, body, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> ReadInt32Async(string port, ReadFieldRequest? body = default, CancellationToken cancellationToken = default)
                => _outer.SendReadInt32Async(port, body, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> WriteFloat32Async(string port, WriteFloat32Request? body = default, CancellationToken cancellationToken = default)
                => _outer.SendWriteFloat32Async(port, body, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> WriteInt16Async(string port, WriteInt16Request? body = default, CancellationToken cancellationToken = default)
                => _outer.SendWriteInt16Async(port, body, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> WriteInt32Async(string port, WriteInt32Request? body = default, CancellationToken cancellationToken = default)
                => _outer.SendWriteInt32Async(port, body, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> WriteStringAsync(string port, WriteMultipleRegistersRequest? body = default, CancellationToken cancellationToken = default)
                => _outer.SendWriteStringAsync(port, body, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> WriteSingleRegisterAsync(string port, WriteUInt16Request? body = default, CancellationToken cancellationToken = default)
                => _outer.SendWriteSingleRegisterAsync(port, body, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> ReadAllRegistersAsync(string slaveIdHex, string port, CancellationToken cancellationToken = default)
                => _outer.SendReadAllRegistersAsync(slaveIdHex, port, cancellationToken);
        }
    }
}
