// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Aida.Api.Client {
    public partial class SystemApi {
        private readonly HttpClient _http;
        private readonly Uri _baseUrl;
        /// <summary>Discriminated per-status result surface; never throws for modeled statuses.</summary>
        public ResultsClient Results { get; }
        /// <summary>Raw HTTP surface; returns the underlying HttpResponseMessage.</summary>
        public RawClient Raw { get; }

        public SystemApi(HttpClient http, Uri baseUrl) {
            _http = http ?? throw new ArgumentNullException(nameof(http));
            _baseUrl = baseUrl ?? throw new ArgumentNullException(nameof(baseUrl));
            Results = new ResultsClient(this);
            Raw = new RawClient(this);
        }

        private async Task<HttpResponseMessage> SendGetSystemModelAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/system/get-system-model";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<string> GetSystemModelAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetSystemModelAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<string>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetSystemModel {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGetSystemSerialAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/system/get-system-serial";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<string> GetSystemSerialAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetSystemSerialAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<string>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetSystemSerial {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGetSystemInfoAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/system/info";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<SystemInfoDto> GetSystemInfoAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetSystemInfoAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<SystemInfoDto>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetSystemInfo {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendSystemResetAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/system/reset";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<SystemStatusDto> SystemResetAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendSystemResetAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<SystemStatusDto>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"SystemReset {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendSetSystemModelAsync(string? model = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/system/set-system-model";
            var __query = new StringBuilder();
            if (model is not null)
            {
                __query.Append("?model=").Append(Uri.EscapeDataString(model ?? string.Empty));
            }
            var __url = new Uri(_baseUrl, __relPath + __query.ToString());
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task SetSystemModelAsync(string? model = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendSetSystemModelAsync(model, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"SetSystemModel {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendSetSystemSerialAsync(string? serial = default, CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/system/set-system-serial";
            var __query = new StringBuilder();
            if (serial is not null)
            {
                __query.Append("?serial=").Append(Uri.EscapeDataString(serial ?? string.Empty));
            }
            var __url = new Uri(_baseUrl, __relPath + __query.ToString());
            using var __req = new HttpRequestMessage(new HttpMethod("POST"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task SetSystemSerialAsync(string? serial = default, CancellationToken cancellationToken = default)
        {
            using var __resp = await SendSetSystemSerialAsync(serial, cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                return;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"SetSystemSerial {__status} {__resp.ReasonPhrase}");
        }

        private async Task<HttpResponseMessage> SendGetSystemStatusAsync(CancellationToken cancellationToken = default)
        {
            var __relPath = $"/aida/v1/system/status";
            var __url = new Uri(_baseUrl, __relPath);
            using var __req = new HttpRequestMessage(new HttpMethod("GET"), __url);
            return await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
        }

        /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">Any non-success status without a declared schema, or a declared schema that fails to deserialize.</exception>
        public async Task<SystemStatusDto> GetSystemStatusAsync(CancellationToken cancellationToken = default)
        {
            using var __resp = await SendGetSystemStatusAsync(cancellationToken).ConfigureAwait(false);
            int __status = (int)__resp.StatusCode;
            if (__status >= 200 && __status < 300)
            {
                using var __stream = await __resp.Content.ReadAsStreamAsync().ConfigureAwait(false);
                var __result = await JsonSerializer.DeserializeAsync<SystemStatusDto>(__stream, JsonConfig.Options, cancellationToken).ConfigureAwait(false);
                return __result!;
            }
            string? __rawBody = null;
            try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
            throw new ApiException((System.Net.HttpStatusCode)__status, __rawBody, $"GetSystemStatus {__status} {__resp.ReasonPhrase}");
        }

        /// <summary>Typed per-status result surface. Result types live in the &lt;c&gt;.Responses&lt;/c&gt; sub-namespace so they never collide with DTO names from the spec.</summary>
        public sealed class ResultsClient {
            private readonly SystemApi _outer;

            internal ResultsClient(SystemApi outer) { _outer = outer; }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetSystemModelResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetSystemModelResult> GetSystemModelAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetSystemModelAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        string? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<string>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetSystemModelResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetSystemModelResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetSystemSerialResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetSystemSerialResult> GetSystemSerialAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetSystemSerialAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        string? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<string>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetSystemSerialResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetSystemSerialResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetSystemInfoResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetSystemInfoResult> GetSystemInfoAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetSystemInfoAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        SystemInfoDto? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<SystemInfoDto>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetSystemInfoResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetSystemInfoResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.SystemResetResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.SystemResetResult> SystemResetAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendSystemResetAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        SystemStatusDto? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<SystemStatusDto>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.SystemResetResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.SystemResetResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.SetSystemModelResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.SetSystemModelResult> SetSystemModelAsync(string? model = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendSetSystemModelAsync(model, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.SetSystemModelResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.SetSystemModelResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.SetSystemSerialResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.SetSystemSerialResult> SetSystemSerialAsync(string? serial = default, CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendSetSystemSerialAsync(serial, cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        return global::Aida.Api.Client.Responses.SetSystemSerialResult.FromOk(__rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.SetSystemSerialResult.FromOther(__status, __rawBody);
                    }
                }
            }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>A discriminated &lt;see cref="global::Aida.Api.Client.Responses.GetSystemStatusResult"/&gt; that never throws for modeled statuses.</returns>
            public async Task<global::Aida.Api.Client.Responses.GetSystemStatusResult> GetSystemStatusAsync(CancellationToken cancellationToken = default)
            {
                using var __resp = await _outer.SendGetSystemStatusAsync(cancellationToken).ConfigureAwait(false);
                int __status = (int)__resp.StatusCode;
                string? __rawBody = null;
                try { __rawBody = await __resp.Content.ReadAsStringAsync().ConfigureAwait(false); } catch { /* ignore */ }
                switch (__status)
                {
                    case 200:
                    {
                        SystemStatusDto? __value = default;
                        if (!string.IsNullOrEmpty(__rawBody))
                        {
                            try
                            {
                                __value = JsonSerializer.Deserialize<SystemStatusDto>(__rawBody!, JsonConfig.Options);
                            }
                            catch { /* keep __value null — will surface as null payload */ }
                        }
                        return global::Aida.Api.Client.Responses.GetSystemStatusResult.FromOk(__value, __rawBody);
                    }
                    default:
                    {
                        return global::Aida.Api.Client.Responses.GetSystemStatusResult.FromOther(__status, __rawBody);
                    }
                }
            }
        }

        /// <summary>Returns the underlying HttpResponseMessage unchanged. Caller must dispose.</summary>
        public sealed class RawClient {
            private readonly SystemApi _outer;

            internal RawClient(SystemApi outer) { _outer = outer; }

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetSystemModelAsync(CancellationToken cancellationToken = default)
                => _outer.SendGetSystemModelAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetSystemSerialAsync(CancellationToken cancellationToken = default)
                => _outer.SendGetSystemSerialAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetSystemInfoAsync(CancellationToken cancellationToken = default)
                => _outer.SendGetSystemInfoAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> SystemResetAsync(CancellationToken cancellationToken = default)
                => _outer.SendSystemResetAsync(cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> SetSystemModelAsync(string? model = default, CancellationToken cancellationToken = default)
                => _outer.SendSetSystemModelAsync(model, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> SetSystemSerialAsync(string? serial = default, CancellationToken cancellationToken = default)
                => _outer.SendSetSystemSerialAsync(serial, cancellationToken);

            /// <param name="cancellationToken">Token to observe while waiting for the HTTP call to complete.</param>
            /// <returns>The raw &lt;see cref="HttpResponseMessage"/&gt;. Caller owns disposal and status handling.</returns>
            public Task<HttpResponseMessage> GetSystemStatusAsync(CancellationToken cancellationToken = default)
                => _outer.SendGetSystemStatusAsync(cancellationToken);
        }
    }
}
