// <auto-generated/>
#nullable enable
using System;
using System.IO;

namespace Aida.Api.Client.Responses {
    /// <summary>
    /// Discriminated response for CreateInkjetLayout. Exactly one of the typed properties corresponding to {Status} will be non-null; the others will be null. Use {Match} for exhaustive handling.
    /// </summary>
    public sealed class CreateInkjetLayoutResult {
        public int Status { get; }
        public string? RawBody { get; }

        public int? Ok { get; }

        public bool IsOk => Status == 200;
        public bool IsSuccessStatus => Status >= 200 && Status < 300;

        private CreateInkjetLayoutResult(int status, string? rawBody, int? ok) {
            Status = status;
            RawBody = rawBody;
            Ok = ok;
        }

        internal static CreateInkjetLayoutResult FromOk(int? value, string? rawBody = null) {
            return new CreateInkjetLayoutResult(200, rawBody, value);
        }

        internal static CreateInkjetLayoutResult FromOther(int status, string? rawBody = null) {
            return new CreateInkjetLayoutResult(status, rawBody, default);
        }

        /// <summary>
        /// Exhaustive match across all declared response variants. The onOther handler covers any status not declared in the OpenAPI spec.
        /// </summary>
        public T Match<T>(Func<int, T> onOk, Func<int, string?, T> onOther)
        {
            if (Status == 200) return onOk(Ok!.Value);
            return onOther(Status, RawBody);
        }
    }
}
