// <auto-generated/>
#nullable enable
using System;
using System.IO;

namespace Aida.Api.Client.Responses {
    /// <summary>
    /// Discriminated response for GetHolderConfigurationTest. Exactly one of the typed properties corresponding to {Status} will be non-null; the others will be null. Use {Match} for exhaustive handling.
    /// </summary>
    public sealed class GetHolderConfigurationTestResult {
        public int Status { get; }
        public string? RawBody { get; }

        public global::System.Collections.Generic.IList<global::Aida.Api.Client.HolderRawConfiguration>? Ok { get; }

        public bool IsOk => Status == 200;
        public bool IsSuccessStatus => Status >= 200 && Status < 300;

        private GetHolderConfigurationTestResult(int status, string? rawBody, global::System.Collections.Generic.IList<global::Aida.Api.Client.HolderRawConfiguration>? ok) {
            Status = status;
            RawBody = rawBody;
            Ok = ok;
        }

        internal static GetHolderConfigurationTestResult FromOk(global::System.Collections.Generic.IList<global::Aida.Api.Client.HolderRawConfiguration>? value, string? rawBody = null) {
            return new GetHolderConfigurationTestResult(200, rawBody, value);
        }

        internal static GetHolderConfigurationTestResult FromOther(int status, string? rawBody = null) {
            return new GetHolderConfigurationTestResult(status, rawBody, default);
        }

        /// <summary>
        /// Exhaustive match across all declared response variants. The onOther handler covers any status not declared in the OpenAPI spec.
        /// </summary>
        public T Match<T>(Func<global::System.Collections.Generic.IList<global::Aida.Api.Client.HolderRawConfiguration>, T> onOk, Func<int, string?, T> onOther)
        {
            if (Status == 200) return onOk(Ok!);
            return onOther(Status, RawBody);
        }
    }
}
