// <auto-generated/>
#nullable enable
using System;
using System.IO;

namespace Aida.Api.Client.Responses {
    /// <summary>
    /// Discriminated response for GetXPrintSystemSettings. Exactly one of the typed properties corresponding to {Status} will be non-null; the others will be null. Use {Match} for exhaustive handling.
    /// </summary>
    public sealed class GetXPrintSystemSettingsResult {
        public int Status { get; }
        public string? RawBody { get; }

        public global::Aida.Api.Client.XPrintSystemSettings? Ok { get; }

        public bool IsOk => Status == 200;
        public bool IsSuccessStatus => Status >= 200 && Status < 300;

        private GetXPrintSystemSettingsResult(int status, string? rawBody, global::Aida.Api.Client.XPrintSystemSettings? ok) {
            Status = status;
            RawBody = rawBody;
            Ok = ok;
        }

        internal static GetXPrintSystemSettingsResult FromOk(global::Aida.Api.Client.XPrintSystemSettings? value, string? rawBody = null) {
            return new GetXPrintSystemSettingsResult(200, rawBody, value);
        }

        internal static GetXPrintSystemSettingsResult FromOther(int status, string? rawBody = null) {
            return new GetXPrintSystemSettingsResult(status, rawBody, default);
        }

        /// <summary>
        /// Exhaustive match across all declared response variants. The onOther handler covers any status not declared in the OpenAPI spec.
        /// </summary>
        public T Match<T>(Func<global::Aida.Api.Client.XPrintSystemSettings, T> onOk, Func<int, string?, T> onOther)
        {
            if (Status == 200) return onOk(Ok!);
            return onOther(Status, RawBody);
        }
    }
}
