// <auto-generated/>
#nullable enable
using System;
using System.IO;

namespace Aida.Api.Client.Responses {
    /// <summary>
    /// Discriminated response for PurgeWorkflowData. Exactly one of the typed properties corresponding to {Status} will be non-null; the others will be null. Use {Match} for exhaustive handling.
    /// </summary>
    public sealed class PurgeWorkflowDataResult {
        public int Status { get; }
        public string? RawBody { get; }


        public bool IsOk => Status == 200;
        public bool IsSuccessStatus => Status >= 200 && Status < 300;

        private PurgeWorkflowDataResult(int status, string? rawBody) {
            Status = status;
            RawBody = rawBody;
        }

        internal static PurgeWorkflowDataResult FromOk(string? rawBody = null) {
            return new PurgeWorkflowDataResult(200, rawBody);
        }

        internal static PurgeWorkflowDataResult FromOther(int status, string? rawBody = null) {
            return new PurgeWorkflowDataResult(status, rawBody);
        }

        /// <summary>
        /// Exhaustive match across all declared response variants. The onOther handler covers any status not declared in the OpenAPI spec.
        /// </summary>
        public T Match<T>(Func<T> onOk, Func<int, string?, T> onOther)
        {
            if (Status == 200) return onOk();
            return onOther(Status, RawBody);
        }
    }
}
