// <auto-generated/>
#nullable enable
using System;
using System.IO;

namespace Aida.Api.Client.Responses {
    /// <summary>
    /// Discriminated response for ToggleLampXpOne. Exactly one of the typed properties corresponding to {Status} will be non-null; the others will be null. Use {Match} for exhaustive handling.
    /// </summary>
    public sealed class ToggleLampXpOneResult {
        public int Status { get; }
        public string? RawBody { get; }

        public global::Aida.Api.Client.ProblemDetails? BadRequest { get; }
        public global::Aida.Api.Client.ProblemDetails? NotFound { get; }
        public global::Aida.Api.Client.ProblemDetails? Conflict { get; }
        public global::Aida.Api.Client.ProblemDetails? UnprocessableEntity { get; }
        public global::Aida.Api.Client.ProblemDetails? InternalServerError { get; }
        public global::Aida.Api.Client.ProblemDetails? ServiceUnavailable { get; }

        public bool IsNoContent => Status == 204;
        public bool IsBadRequest => Status == 400;
        public bool IsNotFound => Status == 404;
        public bool IsConflict => Status == 409;
        public bool IsUnprocessableEntity => Status == 422;
        public bool IsInternalServerError => Status == 500;
        public bool IsServiceUnavailable => Status == 503;
        public bool IsSuccessStatus => Status >= 200 && Status < 300;

        private ToggleLampXpOneResult(int status, string? rawBody, global::Aida.Api.Client.ProblemDetails? badRequest, global::Aida.Api.Client.ProblemDetails? notFound, global::Aida.Api.Client.ProblemDetails? conflict, global::Aida.Api.Client.ProblemDetails? unprocessableEntity, global::Aida.Api.Client.ProblemDetails? internalServerError, global::Aida.Api.Client.ProblemDetails? serviceUnavailable) {
            Status = status;
            RawBody = rawBody;
            BadRequest = badRequest;
            NotFound = notFound;
            Conflict = conflict;
            UnprocessableEntity = unprocessableEntity;
            InternalServerError = internalServerError;
            ServiceUnavailable = serviceUnavailable;
        }

        internal static ToggleLampXpOneResult FromNoContent(string? rawBody = null) {
            return new ToggleLampXpOneResult(204, rawBody, default, default, default, default, default, default);
        }

        internal static ToggleLampXpOneResult FromBadRequest(global::Aida.Api.Client.ProblemDetails? value, string? rawBody = null) {
            return new ToggleLampXpOneResult(400, rawBody, value, default, default, default, default, default);
        }

        internal static ToggleLampXpOneResult FromNotFound(global::Aida.Api.Client.ProblemDetails? value, string? rawBody = null) {
            return new ToggleLampXpOneResult(404, rawBody, default, value, default, default, default, default);
        }

        internal static ToggleLampXpOneResult FromConflict(global::Aida.Api.Client.ProblemDetails? value, string? rawBody = null) {
            return new ToggleLampXpOneResult(409, rawBody, default, default, value, default, default, default);
        }

        internal static ToggleLampXpOneResult FromUnprocessableEntity(global::Aida.Api.Client.ProblemDetails? value, string? rawBody = null) {
            return new ToggleLampXpOneResult(422, rawBody, default, default, default, value, default, default);
        }

        internal static ToggleLampXpOneResult FromInternalServerError(global::Aida.Api.Client.ProblemDetails? value, string? rawBody = null) {
            return new ToggleLampXpOneResult(500, rawBody, default, default, default, default, value, default);
        }

        internal static ToggleLampXpOneResult FromServiceUnavailable(global::Aida.Api.Client.ProblemDetails? value, string? rawBody = null) {
            return new ToggleLampXpOneResult(503, rawBody, default, default, default, default, default, value);
        }

        internal static ToggleLampXpOneResult FromOther(int status, string? rawBody = null) {
            return new ToggleLampXpOneResult(status, rawBody, default, default, default, default, default, default);
        }

        /// <summary>
        /// Exhaustive match across all declared response variants. The onOther handler covers any status not declared in the OpenAPI spec.
        /// </summary>
        public T Match<T>(Func<T> onNoContent, Func<global::Aida.Api.Client.ProblemDetails, T> onBadRequest, Func<global::Aida.Api.Client.ProblemDetails, T> onNotFound, Func<global::Aida.Api.Client.ProblemDetails, T> onConflict, Func<global::Aida.Api.Client.ProblemDetails, T> onUnprocessableEntity, Func<global::Aida.Api.Client.ProblemDetails, T> onInternalServerError, Func<global::Aida.Api.Client.ProblemDetails, T> onServiceUnavailable, Func<int, string?, T> onOther)
        {
            if (Status == 204) return onNoContent();
            if (Status == 400) return onBadRequest(BadRequest!);
            if (Status == 404) return onNotFound(NotFound!);
            if (Status == 409) return onConflict(Conflict!);
            if (Status == 422) return onUnprocessableEntity(UnprocessableEntity!);
            if (Status == 500) return onInternalServerError(InternalServerError!);
            if (Status == 503) return onServiceUnavailable(ServiceUnavailable!);
            return onOther(Status, RawBody);
        }
    }
}
